### PR TITLE
save errno to avoid issues with it being overwritten in sway_log_errno

### PR DESCRIPTION
**Pull request by taiyu-len**
was fiddling around with the logging to make it a bit more convenient to debug
and noticed a small mistake with `sway_log_errno`, as `errno` can get overwritten before we use it.

its been a while since i contributed, but i assume 0.15 is where development is going for now

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Should probably restore it too

**Comment by ascent12** [comment]
It's probably not worth bothering.
You'd normally consider errno useless after any function you call.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
