### PR TITLE
document parse_error in run_command reply

### LINKED ISSUE #5574: parse_error field in run_command reply is undocumented
The `parse_error` field is not documented in [sway(7)](https://github.com/swaywm/sway/blob/master/sway/sway-ipc.7.scd#L88) although [it is added](https://github.com/swaywm/sway/blob/master/sway/commands.c#L528) to the command reply if the command was unsuccessful.

### PR DESCRIPTION
**Pull request by JayceFayne**
fixes #5574

### CODE REVIEW

**Comment by emersion** [comment]
It doesn't seem like this is documented in the i3 IPC manual?

**Comment by JayceFayne** [comment]
Yes `parse_error` is not documented in the i3 IPC manual. I was not sure if it should be documented or not that´s why I opened the issue first. If this was left undocumented intentionally feel free to close this pull request.

**Comment by emersion** [comment]
Since this is an unstable i3 API, I'd rather not document it for now. Thanks for taking the time to send a PR though!

**Comment by ohk2kt3t4** [comment]
@JayceFayne Perhaps ask over at i3 whether it should be documented now?

**Comment by JayceFayne** [comment]
@ohk2kt3t4 Yep, I created [this issue](https://github.com/i3/i3/issues/4166)

**Comment by JayceFayne** [comment]
Hey @emersion, could you reopen this pull since https://github.com/i3/i3/pull/4243 landed?:smile:

**Review by emersion — APPROVED** [review]
Thanks!

**Pull request merged**
