### PR TITLE
Send wl_surface.preferred_buffer_scale

### PR DESCRIPTION
**Pull request by emersion**
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3696

### CODE REVIEW

**Comment by rpigott** [comment]
I take it this obviates a need for #6479? Should we consider sending this event in advance of the first map?

**Comment by emersion** [comment]
> I take it this obviates a need for https://github.com/swaywm/sway/pull/6479?

Kind of but not really: we use the list of entered outputs to compute the preferred scale.

> Should we consider sending this event in advance of the first map?

Yes. That's already the case AFAIK.

**Comment by rpigott** [comment]
> Yes. That's already the case AFAIK.

I don't think so. #6479 only stopped us from sending it for view_child surfaces, like popups. IIRC, this was the only case where we sent an early enter, and it was never sent in weston or mutter hence https://gitlab.freedesktop.org/wayland/wayland/-/issues/133.

**Comment by emersion** [comment]
Ah, sounds like a bug then.

**Comment by emersion** [comment]
Since this also affects fractional-scale, I'll merge this and track the bug in a separate issue: https://github.com/swaywm/sway/issues/7668

**Pull request merged**
