### PR TITLE
handlers: preserve parent pointer value

### PR DESCRIPTION
**Pull request by Hummer12007**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Why?

**Comment by Hummer12007** [comment]
https://github.com/Hummer12007/sway/blob/9e36204b230fb9ecc7eaab55c4eacb457e071cdd/sway/handlers.c#L580 is called with the NULL pointer otherwise.

**Comment by SirCmpwn** [comment]
We should rearrange the container for which fullscreen was set (likely the workspace).

**Comment by Hummer12007** [comment]
@SirCmpwn ?

**Comment by SirCmpwn** [comment]
aight, thanks.

**Pull request merged**
