### PR TITLE
tree/view: ensure view content size is positive

### PR DESCRIPTION
**Pull request by emersion**
Closes: https://github.com/swaywm/sway/issues/7946

### CODE REVIEW

**Comment by Nefsen402** [comment]
I think this is actually a wlroots bug, according to a coredump from a while ago the DRM backend generated an output with a 0x0 size. Unfortunately, I wasn't able to reproduce it since.

**Comment by emersion** [comment]
It's completely possible/valid that an output has a zero size, for instance when it's configured to be powered off before it is plugged in.

**Comment by emersion** [comment]
Besides, it's possible that the output size is too small for the number of tiled toplevels and results in negative sizes. For instance, try starting Sway nested, stacking vertically a lot of terminals with a titlebar, then resizing the Sway output to be smaller. I hit the same assert in that case.

**Comment by Nefsen402** [comment]
Fair, LGTM

**Comment by Nefsen402** [comment]
Thanks!

**Review by Nefsen402 — APPROVED** [review]
Thanks number two cause apparently I need to "finish a review" to merge

**Pull request merged**
