### PR TITLE
add support for named colors

### PR DESCRIPTION
**Pull request by 1ace**

### CODE REVIEW

**Comment by ddevault** [comment]
-1

**Comment by emersion** [comment]
Are those supported by i3?

**Comment by progandy** [comment]
@emersion No, i3 only supports hex colors in in RGB or RGBA with alpha channel.

https://github.com/i3/i3/blob/db0add0f11995d4273c76c3c1ad3ab131cea6a99/libi3/draw_util.c#L86

**Comment by emersion** [comment]
I would've considered merging this if it was for i3 compatibility, but if it's a new feature, then I'm not for this.

Sorry about this! Next time feel free to ask us on IRC or open an issue about new features.

**Comment by 1ace** [comment]
Do you mean sway can't have features that i3 doesn't have? That's seems unnecessarily restrictive.

**Comment by emersion** [comment]
No, it just means @ddevault and I don't like this feature.

**Comment by 1ace** [comment]
That's fair 😅

**Pull request closed without merging**
