### PR TITLE
build: bump wlroots version to 0.8.1

### PR DESCRIPTION
**Pull request by emersion**
Closes: https://github.com/swaywm/sway/issues/4618

### CODE REVIEW

**Comment by ddevault** [comment]
Wait, what's this arch failure about?

**Comment by emersion** [comment]
Meson issue fixed in this PR: https://github.com/mesonbuild/meson/pull/6011

(CI build with the Meson patch: https://builds.sr.ht/~emersion/job/95288#task-wlroots)

**Comment by ddevault** [comment]
Can we update this so that we don't have to be stuck with broken stuff until the next meson release?

**Comment by emersion** [comment]
>Can we update this so that we don't have to be stuck with broken stuff until the next meson release?

Done in https://github.com/swaywm/wlroots/pull/1848

**Comment by ddevault** [comment]
Thanks!

**Pull request merged**
