### PR TITLE
Use automatic surface enter/leave

### PR DESCRIPTION
**Pull request by kennylevinsen**
This is the sway implementation of https://github.com/swaywm/wlroots/pull/2468

### CODE REVIEW

**Comment by emersion** [comment]
This looks pretty good to me from a very quick look. Is there a reason why this is new API, and doesn't completely replace `wlr_surface_{enter,leave}`?

**Comment by kennylevinsen** [comment]
I was mainly unsure if it should be done as a breaking change. I find the old naming (send_*, implying that it's going blindly to do just that) to be a bit misleading with the new behavior.

**Comment by kennylevinsen** [comment]
Ready for review together with wlroots PR.

**Comment by kennylevinsen** [comment]
(If wlroots PR changed to old names is merged, then this PR will not be needed.)

**Comment by emersion** [comment]
Not needed anymore.

**Pull request closed without merging**
