### PR TITLE
Add Turkish Translation for README.md (Latest)

### PR DESCRIPTION
**Pull request by MuhammedTaha02**
Latest version for turkish translate @emersion @fluix-dev

### CODE REVIEW

**Comment by fluix-dev** [comment]
Thanks. you'll still need a review from another Turkish speaker though. I see @04ELY made a PR to add a Turkish translation in the past so maybe they could take a look?

**Comment by 04ELY** [comment]
Hey, sorry my notifications are a bit weird.
Some of the words you use are not actually Turkish.

For example,
"**Konfigürasyon**" (French-origin) is actually "**Yapılandırma**"
And "**distro**" is not Turkish.

Some other little things hanging around,
"**Compile-time dependencies**" is not "Derleme Süresi", the "**dependencies**"(bağımlılıklar) word is missing.
"**binary**" is not Turkish too.
"**Root permissions**" is translated as "**kök izinleri**" in other desktops.
"**Opsiyonel**" (French-origin) should be "**isteğe bağlı**" 

And some of the translations are not in 1:1 meaning.
For example,
Original, "(gdm is known to work fairly well)" 
You wrote, "(gdm ile iyi çalıştığı bilinir)" which means "(known to work well with gdm)"
But actual meaning is, "(gdm'nin oldukça iyi çalıştığı bilinmektedir.)"

See? Subject (Who is working well?) is different.
 
 Maybe check out #6027

**Comment by emersion** [comment]
Okay, closing in favor of https://github.com/swaywm/sway/pull/6027, since that one has made two Turkish speakers happy. @MuhammedTaha02, feel free to add comments on that one if you think there are things that can be improved.

**Comment by MuhammedTaha02** [comment]
> Hey, sorry my notifications are a bit weird.
> Some of the words you use are not actually Turkish.
> 
> For example,
> "**Konfigürasyon**" (French-origin) is actually "**Yapılandırma**"
> And "**distro**" is not Turkish.
> 
> Some other little things hanging around,
> "**Compile-time dependencies**" is not "Derleme Süresi", the "**dependencies**"(bağımlılıklar) word is missing.
> "**binary**" is not Turkish too.
> "**Root permissions**" is translated as "**kök izinleri**" in other desktops.
> "**Opsiyonel**" (French-origin) should be "**isteğe bağlı**"
> 
> And some of the translations are not in 1:1 meaning.
> For example,
> Original, "(gdm is known to work fairly well)"
> You wrote, "(gdm ile iyi çalıştığı bilinir)" which means "(known to work well with gdm)"
> But actual meaning is, "(gdm'nin oldukça iyi çalıştığı bilinmektedir.)"
> 
> See? Subject (Who is working well?) is different.
> 
> Maybe check out #6027

Thank you for reporting my mistakes. We can continue from #6027

**Pull request closed without merging**
