### PR TITLE
Swedish README

### PR DESCRIPTION
**Pull request by eschillus**
Added a swedish README file.

### CODE REVIEW

**Comment by emersion** [comment]
Thanks for the PR! It would be nice if another Swedish speaker could review this translation. :)

**Comment by ErikReider** [comment]
Looks good to me :)

**Comment by eschillus** [comment]
> Thanks for the PR! It would be nice if another Swedish speaker could review this translation. :)

Happy to contribute, @ErikReider seems to approve of the translation. A quick check on google translate could also work to make sure nothing is out of place.

**Comment by eschillus** [comment]
Yeah I don't know why the build failed after I commited this, maybe I should just close this PR and create a new one. Sorry for making a mess with multiple commits and PRs. @emersion

**Review by emersion — APPROVED** [review]
Well, I always prefer if a real Swedish speaker can review the changes, to make sure translations are high quality. Thanks @ErikReider for having a look!

The build failures are unrelated, and got fixed in #6945.

Thanks for you contribution!

**Pull request merged**
