### PR TITLE
README: Added Greek translation

### PR DESCRIPTION
**Pull request by jebediah47**
Added README.gr.md file with Greek(Ελληνικά) translation and added Ελληνικα as a available translated language on the README.md

### CODE REVIEW

**Comment by emersion** [comment]
Thanks! Can another native speaker review this?

**Comment by konstadisto789** [comment]
hello I am a native Greek speaker and I approve this translation

> Thanks! Can another native speaker review this?

**Comment by jebediah47** [comment]
> Thanks! Can another native speaker review this?

may this commit be merged, or does it need more verification of the changes from native speakers?

**Review by emersion — APPROVED** [review]
Thank you both!

**Pull request merged**
