### PR TITLE
Add support for linux-drm-syncobj-v1

### PR DESCRIPTION
**Pull request by emersion**
Depends on https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4715

### CODE REVIEW

**Comment by SMFloris** [comment]
Going to test it out fully later today, but I do get a compiler error currently on the condition: server->features.timeline.

I know this is a draft - so is this just a placeholder to have a check on the timeline feature?

Thanks for your contribution!

**Comment by SMFloris** [comment]
Made the condition server->features.timeline true; I _think_ it sort of improved the flickering, but certainly not made it go away. Tested it with the latest 560 driver. Meanwhile, had to switch to KDE + Egl where the flickering is completely gone.

**Comment by c2h5oh** [comment]
We might still be missing some implementation bits https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4715

**Comment by SMFloris** [comment]
@c2h5oh , ah indeed completely missed that.

Oh well, I'll wait for more progress on that merge request and test more as things are moving forward. I don't know about you guys, but I'm feeling pretty optimistic!

**Pull request merged**
