### PR TITLE
Implement handling of short_text field of i3 input protocol.

### PR DESCRIPTION
**Pull request by DmitriK**
Matches i3bar behavior of setting all blocks to use the short_text if the full
text width does not fit.

### CODE REVIEW

**Comment by ddevault** [comment]
Any sway users who take advantage of this feature who can share their test results?

**Comment by tarmack** [comment]
I want to take advantage of this feature. I tested this pull request but I can't get the `short_text` value to be displayed.

I use Pango markup, including different font sizes (only smaller than the configured font) and I also have quite a few "icons" in my bar. Maybe these are confusing the space estimations?

**Comment by tarmack** [comment]
This works wonderfully now. Thank you!

**Comment by ddevault** [comment]
Thanks!

**Pull request merged**
