### PR TITLE
Spanish translation README

### PR DESCRIPTION
**Pull request by athrungithub**

### CODE REVIEW

**Comment by ddevault** [comment]
Needs links to this translation in the list of translations in the other README files.

**Comment by ddevault** [comment]
Got some feedback from the spanish speaking community that this isn't a very good translation. I'm going to pass on this patch, but thank you.

**Comment by athrungithub** [comment]
Yes, spanish is different in diverse countries. There wil never be a consensus.
Thanks  sway comunity!

**Comment by ReK2Fernandez** [comment]
is not that different as long you follow the international Spanish standards, indeed there are diff slang but is all understandable. With time you can get more into details and regional pick latin american, central American and Iberian Spanish but to start Spanish generic is better than nothing..

**Pull request closed without merging**
