### PR TITLE
Use locale time format for default bar command

### PR DESCRIPTION
**Pull request by mattfbacon**

### CODE REVIEW

**Comment by emersion** [comment]
While I agree 24-hour format is objectively superior, half the rest of the world doesn't agree, so not sure this is worth changing.

**Comment by mattfbacon** [comment]
Hmm, we could use `d_fmt`/`t_fmt` from the locale with something like `date +"$(locale d_t_fmt)"`.

**Comment by emersion** [comment]
Maybe `%X`?

The full list of POSIX-compatible format options is available at https://pubs.opengroup.org/onlinepubs/009695399/utilities/date.html

**Comment by mattfbacon** [comment]
Sounds good. And keep the fixed date format?

**Comment by emersion** [comment]
We could use `%x`, but I don't have a strong opinion either way.

**Comment by mattfbacon** [comment]
Changed to use %x, please squash to merge

**Comment by emersion** [comment]
Can you rebase and squash?

**Comment by mattfbacon** [comment]
OK

**Comment by mattfbacon** [comment]
Sorry, I forgot we said that. I would prefer `%Y-%m-%d %X` because [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) is pretty universal, and in most locales the ordering will not be purely hierarchical when combined with `%X` (e.g., D/M/Y H:M:S rather than strictly decreasing from Year to Second)

We may also want to consider `%F %X`.

> %F     full date; like %+4Y-%m-%d

Or just `%c`.

>  %c     locale's date and time (e.g., Thu Mar  3 23:05:25 2005)

**Comment by emersion** [comment]
Okay, I don't mind either way.

**Review by emersion — APPROVED** [review]
Thanks!

**Pull request merged**
