### PR TITLE
swaymsg: fix get_outputs status code

### LINKED ISSUE #3019: swaymsg -t get_outputs returns 1
It should return 0.

This is due to the `success` function checking if each output object has a `success` field set to true. This isn't the case for output objects.

### PR DESCRIPTION
**Pull request by emersion**
Fixes #3019

### CODE REVIEW

**Comment by catb0t** [comment]
is this not prone to regression? now `success_object` returns true when something failed

**Comment by emersion** [comment]
>is this not prone to regression? now success_object returns true when something failed

Can you give an example? Tried `swaymsg idontexist` and it exits with 1 as expected.

**Comment by emersion** [comment]
To clarify: the new code expects result objects to have a `success` field. Other objects won't be considered as results and won't make `swaymsg` exit with 1 anymore.

**Comment by catb0t** [comment]
I don't have an example (on mobile), it just looks like the fix is with how success-lacking objects are treated in `success` rather than making failure in `get_ex` return true always.

**Comment by Snaipe** [comment]
FWIW, i3-msg treats json objects without a success key as successful, so it's probably fine to assume so. Real IPC failures are going to have `"success": false` and maybe an error string anyways.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
