### PR TITLE
Fix issue #1287

### PR DESCRIPTION
**Pull request by karjonas**
The variable matching is now looping through all variables trying to find the longest possible match.

### CODE REVIEW

**Comment by 4e554c4c** [comment]
The variables should already be added to the list longest->shortest, (see sway/commands/set.c:10)

**Comment by SirCmpwn** [comment]
That hasn't been working right for some time, I think.

**Comment by 4e554c4c** [comment]
Yeah, but the fix should either fix that code or remove it imo

**Comment by SirCmpwn** [comment]
Aye.

**Comment by karjonas** [comment]
It seems like the sorting of variables is already handled so this pull request is pointless. **But**, there is a bug that is due to the code that handles variables with a $ prefix, it missing the last character of the variable name. The issue is sway/commands/set.c:33 should have 'size+1' instead of 'size'. Should I update this PR with the correct fix?

**Comment by SirCmpwn** [comment]
Yes, please do.

**Comment by karjonas** [comment]
That should do it.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
