### PR TITLE
output_damage_whole_container: damage subsurfaces 

### LINKED ISSUE #3537: popup window in gtk and qt apps
sway version 1.0-beta.2-288-g74a4d8e9 
wlroots: commit 77c25c152629e8bd3e8287d86
this no happen in rootston.

gtk3-demo, select gtkentrycompletion
1) open popup (with 't' key)
2) move window, with keybinding or mouse.
background no drawing correct.

It sucess in all popup window that are outside the parent window. 
For example in nautilus preferences in any 'open file' dialog window.

I no get any warning in log, sometimes, get 
`"denying request to set cursor from unfocused client"` from cursor.c

if background is video (example mpv) the window is redraw ok
I read all issues with firefox, intellij, etc. 
I don't where set breakpoint in gdb

### PR DESCRIPTION
**Pull request by RedSoxFan**
Fixes #3537 

This adds an iterative call in `output_damage_whole_container` to
damage the subsurfaces for all visible views that are inside of the
container. This is needed to damage subsurfaces that extend outside the
box of the container. Without this, those subsurfaces will create
artifacts when moving or resizing.

### CODE REVIEW

**Comment by RedSoxFan** [comment]
Thanks for the detailed explanation!

> Damaging view children should probably be done in `desktop_damage_whole_container`.

I ended up putting it in `output_damage_whole_container` instead, which `desktop_damage_whole_container` calls for every output.

**Comment by RedSoxFan** [comment]
I just noticed #1883 is to remove `output_damage_view`. Should I use `output_view_for_each_surface` directly? If so, I could roll #1883 into this PR since `output_damage_from_view` is the only other caller of `output_damage_view`

**Comment by emersion** [comment]
>I just noticed #1883 is to remove output_damage_view. Should I use output_view_for_each_surface directly?

Yeah, why not.

**Comment by RedSoxFan** [comment]
> It depends how far we want to go with this, but: this will work if the container is a view, but it won't work if the container contains multiple views. We'd need to recursively traverse child containers in this case.

Oops. This should be fixed now

> > I just noticed #1883 is to remove output_damage_view. Should I use output_view_for_each_surface directly?
> 
> Yeah, why not.

Changed to using `output_view_for_each_surface` directly. I'll create a follow-up PR for #1883

**Comment by emersion** [comment]
Thanks!

**Pull request merged**
