### PR TITLE
Fix swaylock crashing when plugging/unplugging output

### PR DESCRIPTION
**Pull request by emersion**

### CODE REVIEW

**Comment by Ongy** [comment]
```
(gdb) bt full
#0  0x00007fedad577c09 in wl_proxy_marshal () at /usr/lib/libwayland-client.so.0
#1  0x0000557476b10bad in wl_surface_set_buffer_scale (wl_surface=0x0, scale=1) at /usr/include/wayland-client-protocol.h:3695
#2  0x0000557476b11476 in render_frame (surface=0x557477191320) at ../swaylock/render.c:155
        state = 0x557476d17760 <state>
        buffer_width = 0
        buffer_height = 0
        cairo = 0x557477158640
        arc_radius = 50
        arc_thickness = 10
        type_indicator_border_thickness = 0.0245436933
#3  0x0000557476b1153a in render_frames (state=0x557476d17760 <state>) at ../swaylock/render.c:164
        surface = 0x557477191320
#4  0x0000557476b0fdba in output_scale (data=0x557477191320, output=0x5574771560c0, factor=1) at ../swaylock/main.c:118
        surface = 0x557477191320
#5  0x00007fedaa6b11c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#6  0x00007fedaa6b0c2a in ffi_call () at /usr/lib/libffi.so.6
#7  0x00007fedad57abad in  () at /usr/lib/libwayland-client.so.0
#8  0x00007fedad577679 in  () at /usr/lib/libwayland-client.so.0
#9  0x00007fedad5789b4 in wl_display_dispatch_queue_pending () at /usr/lib/libwayland-client.so.0
#10 0x0000557476b1056e in main (argc=1, argv=0x7ffc1f9f29c8) at ../swaylock/main.c:321
        long_options =
            {{name = 0x557476b13d44 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x557476b13d49 "color", has_arg = 1, flag = 0x0, val = 99}, {name = 0x557476b13d4f "image", has_arg = 1, flag = 0x0, val = 105}, {name = 0x557476b13d55 "scaling", has_arg = 1, flag = 0x0, val = 115}, {name = 0x557476b13d5d "tiling", has_arg = 0, flag = 0x0, val = 116}, {name = 0x557476b13d64 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x557476b13d6c "socket", has_arg = 1, flag = 0x0, val = 112}, {name = 0x557476b13d73 "no-unlock-indicator", has_arg = 0, flag = 0x0, val = 117}, {name = 0x557476b13d87 "daemonize", has_arg = 0, flag = 0x0, val = 102}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        usage = 0x557476b13920 "Usage: swaylock [options...]\n\n  -h, --help", ' ' <repeats 21 times>, "Show help message and quit.\n  -c, --color <rrggbb[aa]>       Turn the screen into the given color instead of white.\n  -s, --scaling      "...
        args = {color = 4294967295, mode = BACKGROUND_MODE_SOLID_COLOR, show_indicator = true}
        background_image = 0x0
        c = -1
        __PRETTY_FUNCTION__ = "main"
        registry = 0x557477154e80
        surface = 0x557476d176e0 <types+128>
(gdb) quit
```

I got this on waymonad trying to hotplug.

**Comment by Ongy** [comment]
On plugin:

wl_shm@4: error invalid size (0)

**Comment by emersion** [comment]
Ready for another review, thanks for you patience.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
