### PR TITLE
More readable code

### PR DESCRIPTION
**Pull request by SpizzyCoder**
Changed variable name from "f" to for example "DetectRaspi"
Changed fprintf(stdout,...) to printf(...) for more readable code and it's basically the same.

### CODE REVIEW

**Comment by emersion** [comment]
>Changed variable name from "f" to for example "DetectRaspi"

NACK, `f` is a common name for `FILE *`. Short names are fine if they are used for local variables.

>Changed fprintf(stdout,...) to printf(...)

OK, why not.

**Comment by SpizzyCoder** [comment]
So should i rename them as they were?

**Comment by emersion** [comment]
Yeah, please drop the commit that does the renaming.

**Comment by SpizzyCoder** [comment]
I'm not sure how to delete the very first commit and leaving the second commit there. I'm very new to git so i appreciate every help i can get.

**Comment by emersion** [comment]
Sure. You can do it with a "drop" instruction via an interactive rebase. Please have a look at https://git-rebase.io/ for an explanation about rebasing.

**Comment by fluix-dev** [comment]
Also, for your second commit, is there a reason you didn't change the following:
```c
swaynag/config.c:237:			fprintf(stdout, "swaynag version " SWAY_VERSION "\n");
swaymsg/main.c:399:			fprintf(stdout, "swaymsg version " SWAY_VERSION "\n");
swaybar/main.c:58:			fprintf(stdout, "swaybar version " SWAY_VERSION "\n");
```

**Comment by SpizzyCoder** [comment]
I didn't looked at those files. I didn't wanted to do too much in one step. But thanks for the reminder! I could do those too.

**Comment by emersion** [comment]
Yes, please do, ideally everything in a single commit.

**Comment by SpizzyCoder** [comment]
Should i do the variable renaming also in the one commit. I really don't want to break something with rebasing and stuff.

**Comment by fluix-dev** [comment]
There shouldn't be any renaming of variables, only `fprintf` -> `printf`. Worst case you just have to do 6 of those one line changes again.

**Comment by SpizzyCoder** [comment]
I think i messed it up. I also think the cleanest way to make my contribution is by closing this pull request and creating a new one with the fprintf changes.

**Comment by emersion** [comment]
No. Instead, try `git reset --hard master` and then re-do your changes from scratch. Then `git push -f`.

**Comment by SpizzyCoder** [comment]
I think that worked. Thank you for your advice and patience!

**Review by fluix-dev — APPROVED** [review]
LGTM, thanks!

**Review by emersion — APPROVED** [review]
Thanks

**Pull request merged**
