### PR TITLE
Chase wlroots!2434 "Assorted borderline bikeshedding breaking API cleanups"

### PR DESCRIPTION
**Pull request by Billli11**
References: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/2434

### CODE REVIEW

**Comment by emersion** [comment]
Hm, the FreeBSD build is failing for some reason… Can you try pushing again? (With a new commit hash, e.g. `git commit --amend` and then leave commit message as-is)

**Comment by Billli11** [comment]
Done but job still failed.

Look like package `x11-servers/xwayland-devel` is do longer in repo.  
FreeBSD Git repositories. [link](https://cgit.freebsd.org/ports/tree/x11-servers/xwayland-devel) return 404 error

**Comment by emersion** [comment]
Ah, maybe we can just use the regular xwayland package now (without -devel)? Could you try that in a separate commit?

**Review by emersion — APPROVED** [review]
Thanks!

**Comment by emersion** [comment]
If you're bored, would be helpful to submit that FreeBSD change back to wlroots :P

**Comment by Billli11** [comment]
Done. [!4747](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4747)

**Pull request merged**
