### PR TITLE
layer-shell: Restore interactive layer focus code

### PR DESCRIPTION
**Pull request by joanbm**
Commit 188811f80861 ("scene_graph: Port layer_shell") accidentally removed code in `arrange_layers` to handle focus on layer shell surfaces with keyboard interactivity.

Due to this, layer shell surfaces requesting exclusive keyboard interactivity may not get automatically focused, and layer shell surfaces giving up exclusive keyboard interactivity can remain focused.

Add the [previous code](https://github.com/swaywm/sway/blob/2c69e19fd30c5ceac61d6af821c6c6875cd3f8b6/sway/desktop/layer_shell.c#L247-L279) back to fix the problem.

Note the non-rename change included in b4d7e84d3852 ("desktop: Rename layers to shell_layers") is not included as it also seems accidental.

Fixes: #7936

### CODE REVIEW

**Comment by joanbm** [comment]
This has the same purpose as #8032 but instead recovers the removed code as-is.

What I mention as "layer shell surfaces requesting exclusive keyboard interactivity may not get automatically focused" can be triggered by running `seq 3 | bemenu --grab`.

**Review by WhyNotHugo — COMMENTED** [review]
I tested 35dd8d002acad34e63f28a6a2da2bf568d631c1b with shotman and it works for me: when shotman sends the request `set_keyboard_interactivity(none)`, focus is properly relinquished.

**Comment by Nefsen402** [comment]
I don't like this because this is just papering over horrible and confusing input code. Ideally, during keypresses we decide what we are focusing in some scene native way, gone are `seat_set_focus_*()`.

But that requires a lot of work, and more importantly, an actual understanding of how focus in sway is supposed to work. Because every time I take a look at the code to try to gain some understanding, I blow a gasket. So as an interim solution, we can keep this.

**Review by Nefsen402 — APPROVED** [review]
Thanks!

**Comment by joanbm** [comment]
> I don't like this because this is just papering over horrible and confusing input code. Ideally, during keypresses we decide what we are focusing in some scene native way, gone are `seat_set_focus_*()`.
> 
> But that requires a lot of work, and more importantly, an actual understanding of how focus in sway is supposed to work. Because every time I take a look at the code to try to gain some understanding, I blow a gasket. So as an interim solution, we can keep this.

Thanks for the review! Indeed, this comes from a place of "let's get this working again" [so I can bear testing the v1.10 branch on my PC] rather than from a place of "let's try to get to an elegant solution".

**Pull request merged**
