### PR TITLE
sway/commands/output: Add command for unplugging non-physical outputs

### PR DESCRIPTION
**Pull request by any1**
Closes: https://github.com/swaywm/sway/issues/5522

### CODE REVIEW

**Review by emersion — APPROVED** [review]
LGTM!

**Comment by mauro3** [comment]
In case someone also wonders how to actually use this feature:
```
swaymsg output HEADLESS-1 unplug
```

**Comment by fritzrehde** [comment]
I'm not sure if this is a bug or a feature, but after unplugging using `swaymsg output HEADLESS-1 unplug`, creating a new output again using `swaymsg create_output` will increment the number appended to `HEADLESS-<num>` everytime. So after unplugging `HEADLESS-1`, `HEADLESS-2` will be created next. This seems unideal for scripting purposes. Is there a way to properly remove `HEADLESS-1`, so I can continue using it once I use `swaymsg create_output` again? Or is there something more like `swaymsg output HEADLESS-1 plug`?

**Comment by Riolku** [comment]
@fritzrehde Unfortunately it seems [part of wlroots](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/backend/headless/output.c#L131). I think ill just use a small bash script with `swaymsg` and `jq`.

**Comment by fritzrehde** [comment]
@Riolku Can you share the script you eventually come up with here then? Would be curious to see it

**Comment by Riolku** [comment]
Haven't gotten a chance to iron it out, but you can get the active HEADLESS output with `swaymsg -t get_outputs | jq .[].name | grep HEADLESS | tr -d '"'`

"Get outputs and get the names of the outputs and look for the headless one and trim the double quotes"

**Comment by fritzrehde** [comment]
I don't quite understand the reasoning behind incrementing though. Could someone explain that?

**Comment by Riolku** [comment]
No chance of collision.

**Comment by fritzrehde** [comment]
> Haven't gotten a chance to iron it out, but you can get the active HEADLESS output with `swaymsg -t get_outputs | jq .[].name | grep HEADLESS | tr -d '"'`
> 
> "Get outputs and get the names of the outputs and look for the headless one and trim the double quotes"

Ok, but the issue is more: How do I write e.g. a kanshi profile for the headless output? Or even just an output configuration in the sway config file?

**Comment by Riolku** [comment]
I don't know what your use case is, but maybe this extended discussion is better in IRC. Feel free to ping me there.

**Comment by rodhfr** [comment]
here's my script for using with wayvnc
```bash
#!bin/bash
pkill wayvnc
swaymsg create_output

# Get the list of output names containing "HEADLESS", ignoring the first one
headless_outputs=$(swaymsg -t get_outputs | jq -r '.[].name' | grep HEADLESS | tail -n +2)

# Loop through the outputs (starting from the second one)
for i in $headless_outputs; do
    swaymsg output "$i" unplug
done

swaymsg -t get_outputs
swaymsg output "HEADLESS-1" resolution 1920x1080
nohup wayvnc -o HEADLESS-1 &
```

**Pull request merged**
