### PR TITLE
advertize dependency on git

### PR DESCRIPTION
**Pull request by Arnaudv6**
sway depends on git for version information

### CODE REVIEW

**Comment by emersion** [comment]
Can you squash these commits together?

**Comment by Arnaudv6** [comment]
working through the website here, not git: not sure how to do that?

**Comment by emersion** [comment]
I just squashed them. Next time please don't use the GitHub UI.

**Comment by emersion** [comment]
Thanks!

**Comment by Arnaudv6** [comment]
I'll try, thanks!

**Pull request merged**
