### PR TITLE
Fix build on FreeBSD adjusting/removing _XOPEN_SOURCE declaration.

### PR DESCRIPTION
**Pull request by johalun**
Reference #1396

### CODE REVIEW

**Comment by Zer0-One** [comment]
You probably don't want to avoid defining that on *everything* except Linux, you just want to avoid defining it on FreeBSD. And before doing that, you might want to ask the FreeBSD people about their SUSv4 compliance.

**Comment by johalun** [comment]
Changed to not freebsd and added a comment so we'll know why. maybe there's a better solution but this is what I got so far..

**Comment by myfreeweb** [comment]
Uhhh I guess you missed what I ended up doing in wlroots:

```c
#ifdef __FreeBSD__
#define __BSD_VISIBLE 1
#endif
```

**Comment by johalun** [comment]
@myfreeweb 
> #define __BSD_VISIBLE 1
It solves the problem but I don't think we should define things that are internal to the implementation.

**Pull request merged**
