### PR TITLE
[WIP] make xwayland optional

### PR DESCRIPTION
**Pull request by armtux**
Please note that I was running a previous version of these changes on a Raspberry Pi 3 without issues and have not been able to test this latest work because while sway compiles fine it won't start anymore, and I'd like advice with regards to these changes if you think they are the cause of breakage. I have spoken to emersion and he suggests I make a PR for further discussion.

### CODE REVIEW

**Comment by emersion** [comment]
>it won't start anymore

Can you post the stack trace?

**Comment by ppascher** [comment]
Thank you! I just used your PR and adjusted it to current master. Sway compiled and starts fine now.

Here is a git diff if that helps:
https://gist.github.com/ppascher/0efdd6ad36f8540c8073704d4f8ad7f4

**Comment by emersion** [comment]
@ppascher Can you open a PR please?

**Comment by RyanDwyer** [comment]
Superseded by #2350.

**Pull request closed without merging**
