### PR TITLE
[WIP] Update translations and add DEPENDENCIES.md.

### LINKED ISSUE #3965: Discussion of README translations.
I alluded to this in https://github.com/swaywm/sway/pull/3922#issuecomment-473652064.

Some translations of the README are outdated and still reference wlc, others are pretty much 1:1 with the English version. I think if you're monolingual in one of these languages with an outdated README, the outdated translations might just end up misleading you.

It's excellent that there are so many translations available, but keeping them maintained is difficult. There's also the question of how often these translations are used.

I guess this is kind of an RFC about what/if we can do anything about this.

### PR DESCRIPTION
**Pull request by c-edw**
Closes #3965.

Summary:
- Removed references to the bounty program (https://github.com/swaywm/sway/issues/986) which is now closed
- Removed a `setcap` command which doesn't appear to be relevant anymore
- Removed a screenshot from all translations (I thought this was a nice touch but it isn't in the main README anymore)
- Minor formatting changes
- Added `DEPENDENCIES.md` which aims to contain a language-independent list of dependencies
    - `?` is used to denote optional dependencies as it's more universal

Issues:
- `DEPENDENCIES.md` 
    - Isn't quite language-independent
    - Is referenced in all translations but in English, will need to be translated by individuals

I suspect this will need some changes so I'm marking it as WIP.

### CODE REVIEW

**Comment by sviatniy** [comment]
I can take care of the ukrainian README. I have it fixed in [this commit](https://github.com/sviatniy/sway/commit/89f001a8f4f0336660973e532eded5da456a69e3) (its based on current `master` branch, without reference to `DEPENDENCIES.md`). I can update when you decide on the proper format or you can just copy the changes from there.

**Comment by emersion** [comment]
I'm not a fan of splitting the `README.md` into two files.

**Comment by ddevault** [comment]
Neither am I.

**Comment by emersion** [comment]
Still interested in removing stuff from outdated READMEs, though.

**Pull request closed without merging**
