### PR TITLE
Force bilinear scaling when scaling down

### PR DESCRIPTION
**Pull request by Nefsen402**
Untested

### CODE REVIEW

**Review by emersion — APPROVED** [review]
Works, and mirrors what Sway 1.8 was doing with MIN/MAG_FILTER.

Thanks!

**Comment by Nefsen402** [comment]
Scaling mode won't make a difference if there is scaling unless there is a bug in a renderer that stretches the texture randomly by one pixel.

**Comment by akelmanson** [comment]
downscaling with nearest filter (waybar): 👎
image

downscaling with bilinear filter (waylar): 👍
image

buffer already scaled by the client with bilinear filter (chrome): 👎 (blur)
image

buffer already scaled by the client with nearest filter (chrome): 👍
image

do you it's a bug in the renderer?

**Comment by Nefsen402** [comment]
It might also be caused by a slightly shifted position causing the texture to be sampled between texels. But I don't feel like tracking down why a texture might be shifted by .5 pixels.

**Comment by Nefsen402** [comment]
In that case, it might be a good idea to open a PR with your suggested change with this change:

```
	if ((buffer->dst_width == 0 && buffer->dst_height == 0) || (
			buffer->buffer_width == buffer->dst_width &&
			buffer->buffer_height == buffer->dst_height
	)) {
		return WLR_SCALE_FILTER_NEAREST;
	}
```

This PR simply restores prior behavior.

**Pull request merged**
