### PR TITLE
color management

### PR DESCRIPTION
**Pull request by akvadrako**
This adds basic color management to sway. It's a companion to https://github.com/swaywm/wlroots/pull/2353.

Basically it just adds two options which control the ICC profile assigned to views and outputs, which are passed into wlroots where the conversion is done:

```
output * {
    color profile "edid-28a128-PHL-326M6V.icc"
}

for_window [title="glmark2"] {
    color profile "invert-22.icc"
}
```

See also: #1486.

### CODE REVIEW

**Comment by hajosattila** [comment]
_output * {
    color profile "edid-28a128-PHL-326M6V.icc"
}_

Sorry for the lame question, but how can I use a custom route?

**Comment by BlitDev** [comment]
When will it be merged?

**Comment by FelixPehla** [comment]
support for color management has been merged in #7681 , so I assume this can be closed?

**Comment by emersion** [comment]
Indeed, this has been superseded!

**Pull request closed without merging**
