### PR TITLE
[WIP] Implement seat detach

### PR DESCRIPTION
**Pull request by madblobfish**
I played around with seats and was badly missing this command.
I'm unsure if this is implemented correctly.

It works, but leaves empty seats behind.

### CODE REVIEW

**Comment by madblobfish** [comment]
Seems to be stable now. Please review if my memory management is fine.
Should empty seats be removed?

**Comment by SirCmpwn** [comment]
I don't think empty seats should be removed.

**Comment by SirCmpwn** [comment]
Actually, maybe they should.

**Comment by SirCmpwn** [comment]
Does this code actually update the wlroots seat?

**Comment by madblobfish** [comment]
@emersion Ok, I'll write a function for destroying/removing empty seats
@SirCmpwn Not sure, how do I check?

Edit:
I think it does because:
- apply_seat_config is called which calls
- input_manager_apply_seat_config which calls calls some methods few functions further down which seem to directly modify wlroots seats

**Comment by SirCmpwn** [comment]
Okay, cool. And yeah, it should destroy the seat. I assume using any seat command on a nonexistent seat will create that seat, so you could recreate destroyed seats - right?

**Comment by madblobfish** [comment]
Sorry, I could not seat cleanup get it to work properly (see my try 2e839b2).
@SirCmpwn Destroyed seats can be recreated. Not sure if this works in all places.

**Comment by madblobfish** [comment]
So more information:
when removing the last device from a seat i get either a crash or other strange behavior.
Here is my config, the debug log and a stack trace: https://gist.github.com/madblobfish/f6188bf61f7eb97ccdf30a092dd41204

**Comment by NilsIrl** [comment]
I don't know if I am using seats incorrectly but in my (maybe incorrect) use case, this would be nice.

Is there a way to not notify a window that it lost focus? Because the would be a solution that doesn't require seats for my use case.

**Comment by ddevault** [comment]
>Is there a way to not notify a window that it lost focus

wl_keyboard.leave

**Comment by NilsIrl** [comment]
> wl_keyboard.leave

Sorry I am a total noob at Wayland. Am I supposed to make a wayland client here or what configuration file do I need to change?

**Comment by ddevault** [comment]
Oh, you want to be notified via IPC. You could just look to see when a different window is focused and infer that the previously focused window lost it.

**Comment by NilsIrl** [comment]
> Oh, you want to be notified via IPC. You could just look to see when a different window is focused and infer that the previously focused window lost it.

I want to prevent a window from knowing it is out of focus.

**Comment by ddevault** [comment]
No, there's no way to do that. I'm not really interested in adding a way, either.

**Comment by floyza** [comment]
@madblobfish if you're not working on this anymore, is it fine with you if I open a new pull request using your work here?

**Comment by madblobfish** [comment]
@floyza I'm not working on this. You can do what you like with my changes.

**Pull request closed without merging**
