### PR TITLE
[WIP] Add security features

### PR DESCRIPTION
**Pull request by ddevault**
- [x] sway-security(7)
- [x] Load security configs
- [x] `permit` and `reject` commands
- [x] Set up Wayland socket for clients on their behalf
- [ ] Apply global filters
- [ ] `-Dinsecure`
- [ ] Lock down fullscreen

Later:

- [ ] Add IPC security features

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Note to self: the bitfield of permitted features will be arrived at via `((default_policy.permit_features & ~default_policy.reject_features) | program_policy.permit_features) & ~program_policy.reject_features`.

**Comment by SirCmpwn** [comment]
My intention is to finish this before the week is through.

**Comment by SirCmpwn** [comment]
As I'm working through this, the infancy of this plan is starting to dawn on me. I think I want to remove this from the 1.0 milestone and postpone it while we put together a design which we can bring to all Wayland compositors.

**Comment by c-edw** [comment]
I was recently looking into `seccomp`, could it be useful here? Though, it's a Linux kernel feature, so BSD users will miss out.

**Comment by emersion** [comment]
>I was recently looking into seccomp, could it be useful here? Though, it's a Linux kernel feature, so BSD users will miss out.

No, `seccomp` are useful for sandboxes, we're not a sandbox.

**Comment by c-edw** [comment]
@emersion It is certainly used in sandboxes, but it seems it can be used a process to restrict it's own capabilities.

**Comment by emersion** [comment]
We don't need to do that. It's not our job.

**Comment by emersion** [comment]
When this is ready, I'd like a real-world example of how this can be useful, e.g. running a restricted Wayland client in a chroot.

**Comment by emersion** [comment]
This won't work well for users who want their service manager to manage clients (e.g. swaylock).

**Comment by ddevault** [comment]
How so?

**Comment by ddevault** [comment]
Ah.

**Comment by ddevault** [comment]
I think that gets back to the "we could have a protocol for creating authorized Wayland sockets to pass to your client's child", though per the discussion before we will likely need to consider this some kind of "superuser" protocol where the user is assumed to have access to everything.

**Pull request closed without merging**
