### PR TITLE
Add virtual keyboard protocol

### PR DESCRIPTION
**Pull request by SirCmpwn**
Ref #2373 

To test use [virtboard](https://source.puri.sm/Librem5/virtboard)

cc @dcz-purism

### CODE REVIEW

**Comment by JonnyMako** [comment]
So, I'm trying to use `virtboard` but I get this message. Is this a regression? Am I missing components?
```
No input method manager global, some functionality unavailable
Could not register to session manager: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
```

**Comment by dcz-purism** [comment]
These messages come from virtboard. The first one is talking that the input-method protocol is not implemented, and the other one is about missing `org.gnome.SessionManager` dbus interface. It should be working fine despite both, is it?

**Comment by dcz-purism** [comment]
Can you check if the dbus invokation works?

```
busctl call --user sm.puri.OSK0 /sm/puri/OSK0 sm.puri.OSK0 SetVisible b true
```

**Comment by JonnyMako** [comment]
@dcz-purism sorry I missed your reply. That still does not work:
```
The name sm.puri.OSK0 was not provided by any .service files
```

**Comment by ianyfan** [comment]
Sanity check that you're doing the busctl call *after* running virtboard?

**Comment by kosciak9** [comment]
Hey @ianyfan I'm having same issue. Running `v1.0-3` straight from Arch repos with `virtboard v0.0.5`. Running `virtboard` produces:

```
No input method manager global, some functionality unavailable
Could not register to session manager: Cannot invoke method; proxy is for the well-known name org.gnome.SessionManager without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag

(process:8181): GLib-CRITICAL **: 17:49:32.580: g_source_remove: assertion 'tag > 0' failed

(process:8181): GLib-GObject-CRITICAL **: 17:49:32.581: g_object_set: assertion 'G_IS_OBJECT (object)' failed
wl_surface@18: error 0: Specified scale value (0) is not positive
```

and running `busctl call --user sm.puri.OSK0 /sm/puri/OSK0 sm.puri.OSK0 SetVisible b true` produces no output as if it went fine. Keyboard is not showing up though.

**Comment by kosciak9** [comment]
Okay, I feel ashamed, but I was running `virtboard-git` not `virtboard`. Switched packages and it works fine now.

**Pull request merged**
