### PR TITLE
swaybar: disallow left and right position and print error on default

### LINKED ISSUE #2878: swaybar: Right anchor displays incorrectly.
When swaybar is configured to display on the right side of the screen, it will instead display at the top, and applications will overlay it.

Version:
```
swaybar version 1.0-alpha.6-304-g30dbb8eb (Oct 18 2018, branch 'master')
```

Steps to reproduce:
1. Define `position right` in the `bar` block of your Sway config
2. Reload the configuration file however you like
3. Observe that the bar displays at the top of the screen as if `position top` was defined
4. Observe that applications overlay the bar
5. ~~Observe that `position left` works correctly~~

### PR DESCRIPTION
**Pull request by Emantor**
The positions "left" and "right" are not allowed by the man page, remove them
from the allowed positions. Also print an error to stderr if we default to the
bottom position.

Fixes #2878

### CODE REVIEW

**Comment by Emantor** [comment]
@ianyfan We could also exit instead of defaulting to bottom, I decided to keep the existing behaviour here. What is your opinion on that?

**Comment by Emantor** [comment]
I think both should be removed. I'll add the `wlr_log` for `commands/bar/position.c`, but I don't think that will work for swaybar, since afaik `wlr_log` is only available to the compositor. I think printing to `stderr` is the right call there.

**Comment by emersion** [comment]
>afaik wlr_log is only available to the compositor

It's also available in clients. But it makes clients link with wlroots, which is not great.

**Comment by Emantor** [comment]
Swaybar does currently not link against wlroots, so i'd like to avoid that dependency.

**Comment by Emantor** [comment]
I removed the allowed positions from sways command. The command already returns an error for invalid positions, so imo no change is needed there. Should be ready for review.

**Comment by RyanDwyer** [comment]
> Swaybar does currently not link against wlroots

I don't know where you're getting your information from. It's linked in `swaybar/meson.build`, and if you search the `swaybar` directory for `wlr_log` you'll see it's used dozens of times.

**Comment by Emantor** [comment]
> > Swaybar does currently not link against wlroots
> 
> I don't know where you're getting your information from. It's linked in `swaybar/meson.build`, and if you search the `swaybar` directory for `wlr_log` you'll see it's used dozens of times.

I did `rg "wlr*.h"` in the swaybar directory, however `*` does not match `/` and since the include path is `wlr/util/log.h` I assumed that swaybar is not linked against wlroots.

I replaced the `fprintf` with `wlr_log`, sorry for the noise.

**Comment by emersion** [comment]
Thanks!

**Pull request merged**
