### PR TITLE
commands: disallow runtime include

### PR DESCRIPTION
**Pull request by RPigott**
Simple fix for #5569 if this is what we want.

### CODE REVIEW

**Comment by synaptiko** [comment]
I was relying on this behavior to have a switcher of color schemes during the runtime, I overcome the limitation of loading a file only once by generating unique file names to be included: https://github.com/synaptiko/.files/blob/master/0-theme/switch-sway.js#L45

I would welcome this back but otherwise I need to find a different method how to achieve the same.

**Comment by Geo25rey** [comment]
@synaptiko I believe the following can work for you.

Add the following lines to your config:
```
set $chosen-theme-link ~/.sway/theme
set $theme-path ~/.sway/theme-to-include
set $theme-keybind $mod+i

include $chosen-theme-link

bindsym $theme-keybind exec 'rm -f $chosen-theme-link; ln -s $theme-path $chosen-theme-link; swaymsg reload'
```

`$chosen-theme-link` is a symbolic link to your current theme config file. `$theme-path` is the actual theme config file. `$theme-keybind` is a keybind to switch to the the theme.

All you need to do is change the variables to the paths and keybinds you want.

**Comment by synaptiko** [comment]
@Geo25rey Thank you, I had this initially but I didn't like the need to call `reload` (it was messing up with some things previously). I already implemented a solution without `include`, I just "parse" the config and run the commands to change colors one by one (which is good enough for my needs): https://github.com/synaptiko/.files/blob/7e571a48f303dc608e2aca0fdcce8333d1f6cd76/0-theme/switch-sway.js#L43-L65

**Comment by Geo25rey** [comment]
@synaptiko it seems between the JavaScript code and the source code of swaymsg there is redundant argument parsing. Maybe you can base your code off of the swaymsg source code for increased efficiency.

**Pull request merged**
