### PR TITLE
root: destroy fallback_output on root_destroy

### PR DESCRIPTION
**Pull request by t2b3**
This fixes memory leaks.

### CODE REVIEW

**Comment by emersion** [comment]
We should be able to clean that up with `output_destroy()`.

**Comment by t2b3** [comment]
Thanks for your reply. Where should I place the `output_destroy()`? I am not sure about the right place.

**Comment by t2b3** [comment]
I tried several ways, but I always end up with some issues, like `wlr_output` of `fallback_output` must be destroyed first but if I do this `output_destroy()` tries to access this freed resource. There must be a proper way to remove the `fallback_output` from `root` but I cannot find out.

**Comment by t2b3** [comment]
I still need to find a good approach to solve this problem. For the meantime, I withdraw this PR.

**Pull request closed without merging**
