### PR TITLE
Send disabled output available modes on IPC get_outputs

### LINKED ISSUE #4057: No mode information on disabled output
When an output is disabled on Sway, it provides no information whatsoever about the output. Example: I want to get available modes on a disabled output to choose the best resolution to enable it, but the `modes` attribute comes empty (`[]`).

* Sway Version: 1.0
* Configuration File: N/A
* Steps to reproduce:
1. `swaymsg output <name> disable`
2. `swaymsg -t get_outputs`

The latter displays no information besides the output is inactive. If enabling the output through `swaymsg output <name> enable`, I can then read available modes, but it is very annoying to have a three step (`enable`, `get_outputs`, `disable`) process just to detect resolutions.

Edit: modes are still available through `/sys/class/drm/card0-<name>/modes`, but then I have to query two different sources at different times to obtain available modes.

For the record, `xrandr` is able to list available modes for disconnected outputs.

### PR DESCRIPTION
**Pull request by ranisalt**
Fixes #4057

### CODE REVIEW

**Comment by RedSoxFan** [comment]
Actually before this gets merged, can you please add a trailing `\n` to the following line to fix the formatting of the swaymsg output?

https://github.com/swaywm/sway/blob/b2cfcebef61087f819b55d2f815e62aa4a6f1a52/swaymsg/main.c#L233

**Comment by ranisalt** [comment]
@RedSoxFan done!

**Comment by RedSoxFan** [comment]
Can you squash the two commits together and force push?

**Comment by ranisalt** [comment]
Can't you do that on the merge dialog? I can do it if not, surely.

**Comment by RedSoxFan** [comment]
> Can't you do that on the merge dialog? 

Yes, but the default message will be a list of all the commit messages. These are often intermediate commit messages that do not matter or can be presented in a better manor. We usually request the author of the PR squash the commit as it allows for them to express the commits cleaner and allows us to merge the PR without having to rewrite the commit messages. The author usually has a better idea of what the important information related to the commit is.

**Comment by RedSoxFan** [comment]
Thanks!

**Comment by ranisalt** [comment]
Sure, understood :smile:

**Pull request merged**
