### PR TITLE
Drop gtk-primary-selection support

### PR DESCRIPTION
**Pull request by ifreund**
See: https://github.com/swaywm/wlroots/issues/2421 https://github.com/swaywm/wlroots/pull/2460

### CODE REVIEW

**Review by emersion — APPROVED** [review]
LGTM, thanks!

**Comment by luispabon** [comment]
This PR broke copying URLs from firefox's URL bar.

**Comment by Emantor** [comment]
> This PR broke copying URLs from firefox's URL bar.

Unless your distribution has gtk3 version 3.24.24, this will remain broken. This will break lots of users using some kind of PPA-like infrastructure but having the main system on a "stable" version, i.e. Ubuntu, Debian, …

Nothing to be done here though, Sway depends on bleeding edge libraries on master.

**Comment by luispabon** [comment]
Unfortunately not, Ubuntu 20.04 ships with  3.24.20 :/

**Pull request merged**
