### PR TITLE
Disable unneeded wlroots subproject features

### PR DESCRIPTION
**Pull request by emersion**

### CODE REVIEW

**Comment by ianyfan** [comment]
What if we want these options enabled?

**Comment by emersion** [comment]
You can override them, they're just defaults. Also, this only happens when a subproject is used. Building wlroots and building wlroots as a subproject are completely separate, build files are at different locations.

If you build sway, I don't think you'll ever want to have `sway/build/subproject/wlroots/rootston/rootston`.

**Comment by ianyfan** [comment]
Meh, I do this so that I can have access to rootston for testing without having to build wlroots separately.

**Comment by ianyfan** [comment]
But I am not against this change

**Comment by ddevault** [comment]
Thanks!

**Comment by JonnyMako** [comment]
I think this is breaking the build for me:
```
Program git found: YES (/usr/bin/git)

|
|Executing subproject wlroots 
|
|Value disabled is not boolean (true or false).
|
|Subproject wlroots is buildable: NO (disabling)
Dependency wlroots found: NO (tried pkgconfig and cmake)

meson.build:73:1: ERROR:  Dependency "wlroots" not found, tried pkgconfig and cmake
```

**Comment by emersion** [comment]
Which version of Meson do you have?

**Pull request merged**
