### PR TITLE
Disconnect swaybg instead of killing it

### PR DESCRIPTION
**Pull request by emersion**
This is much more reliable. This also fixes race conditions when killing swaybg
while it's doing a wl_display_roundtrip.

### CODE REVIEW

**Comment by RedSoxFan** [comment]
I'm getting defunct swaybg processes with this when the output config changes, an output is unplugged, and after reloads

**Comment by emersion** [comment]
Ah, yes. Hrm, we need to double-fork and `waitpid`.

**Comment by emersion** [comment]
Should be fixed now.

**Comment by RedSoxFan** [comment]
Thanks!

**Pull request merged**
