### PR TITLE
Patch #1507: Clicking on invisible title bars switches focus

### PR DESCRIPTION
**Pull request by AGausmann**
The initial problem that sparked #1507 was when I had views inside a container inside a tabbed container and could focus those views by clicking in their title bar region when the tab wasn't focused. This patch resolves that bug, but the issue remains open because there is a lot more to fix in those scenarios.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Can you retarget this against the 0.15 branch instead of master? Also, I'm pretty busy right now, it would save me review time if you could write up a test plan for verifying this change.

**Comment by AGausmann** [comment]
Rebasing, give me a second.

**Comment by AravK** [comment]
Bump! Please integrate this, as till then rock-solid tab splitting functionality is not quite rock-solid.
Tab splitting is awesome but without this patch we cannot really do too many kind-of-largu things at a time.

**Comment by SirCmpwn** [comment]
Have you tested it, @AravK?

**Comment by AravK** [comment]
My original Firefox issue isn't occuring any more, so yay! Nothing's broken, as far as I can tell.
Keeping multiple splits of terminals open behind a Firefox session and clicking on tabs isn't clicking through. This patch works!

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
