### PR TITLE
swaybar: fix binding to wl_pointer multiple times

### LINKED ISSUE #2741: swaybar: after a while, a click causes multiple events
I'm assuming that this is due to hotspots not being removed properly, but I can't reliably reproduce it yet.

### PR DESCRIPTION
**Pull request by emersion**
To reproduce, suspend multiple times your computer and try using your mouse wheel on swaybar to switch between workspaces. It switches multiple times.

Fixes #2741

### CODE REVIEW

**Comment by ianyfan** [comment]
Does this fix https://github.com/swaywm/sway/issues/2741? It seems like it should.

**Comment by emersion** [comment]
Oh, yeah probably. Can you confirm?

**Comment by ianyfan** [comment]
I'll test it

**Comment by ianyfan** [comment]
You're releasing the old pointer event if `seat_handle_capabilities` is called for a non-pointer. I think you need to move that block into the next block.

**Comment by emersion** [comment]
I don't get it. `seat_handle_capabilities` isn't called "for a non-pointer". The `capabilities` event is sent whenever the seat changes its capabilities, e.g. when a pointer (mouse, touchpad) is connected or disconnected. If the seat still has the "pointer" capability, the pointer will get re-created right away.

**Comment by ianyfan** [comment]
Might have something to do with having multiple seats, perhaps? If I add some logging, I get this at startup:

```
2018-10-06 18:38:13 - [swaybar/bar.c:292] adding pointer for 0x607000001670
2018-10-06 18:38:13 - [swaybar/bar.c:287] releasing pointer for 0x6070000016e0
```
which results in there being no pointer at the start.
(just used pointer values for the seats because I'm not sure what other property to use)

**Comment by emersion** [comment]
Yeah, multiseat isn't handled by swaybar, since we use a global `bar->pointer.pointer`. We should use a per-seat state instead. This is a separate issue though.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
