### PR TITLE
Add Persian README file.

### PR DESCRIPTION
**Pull request by mhdzli**
This is not much but I want to thank you for sway.

### CODE REVIEW

**Review by hakhalili — APPROVED** [review]

**Comment by emersion** [comment]
Duplicate of https://github.com/swaywm/sway/pull/6323. I'm not sure which one has the best translation, please feel free to comment.

**Comment by mhdzli** [comment]
@emersion 
Persian documents should be written right to left so the html tags are necessary.
The differences in transacted  texts are more in writing styles and both are correct.

**Review by siruidops — APPROVED** [review]
I have now seen this pull request. mhdz is right. These were the problems that I ignored. This text is better

**Comment by AliChraghi** [comment]
your PR is better so I close #6323

**Review by AliChraghi — APPROVED** [review]

**Comment by emersion** [comment]
@mhdzli, can you rebase against master?

**Comment by mhdzli** [comment]
@emersion 
I deleted the forked repository so I think I should  fetch this PR, merg the commits and make a new one as it mentioned in [github docs](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally#modifying-an-inactive-pull-request-locally). Is there any other way?

**Comment by AliChraghi** [comment]
> @emersion
> I deleted the forked repository so I think I should fetch this PR, merg the commits and make a new one as it mentioned in [github docs](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally#modifying-an-inactive-pull-request-locally). Is there any other way?

you can refork and create another PR

**Comment by mhdzli** [comment]
Replaced with #6428

**Pull request closed without merging**
