### PR TITLE
Allow both BackSpace and Shift+BackSpace to be bound

### LINKED ISSUE #3079: Can't toggle windows between tiling/floating modes
Sway version: sway version 1.0-beta.1-145-gd0bb4506 (Nov  5 2018, branch 'master')
sway config https://pastebin.com/yeaLr5Qx
sway log https://pastebin.com/d0gZnVpa

Can't toggle windows between floating tiling modes unless I comment out my keyboard input in config file or "bindsym $mod+space focus mode_toggle".

Steps to reproduce:
1.Open any window
2.Press $mod+Shift+space

### LINKED ISSUE #3705: Cannot bind both BackSpace and Shift+BackSpace
* Sway Version: recent master, at https://github.com/swaywm/sway/commit/5c78e5cd2c0347873d24e862bfa677bed619bc94, plus another commit to add some logging: https://github.com/bchallenor/sway/commit/c62ee22ae4693275b572de41ed9ef985c44daa2a

* Configuration File:
```
bindsym BackSpace nop 'BackSpace'
bindsym Shift+BackSpace nop 'Shift+BackSpace'

bindsym q exit
```

* Steps to reproduce
1. Start sway with the above config (and logging patch)
2. Press Shift+BackSpace
3. sway should log `nop 'Shift+BackSpace'`, but it actually logs `nop 'BackSpace'`.

* Debug Log:
```
2019-02-16 21:19:48 - [sway/server.c:211] Running compositor on wayland display 'wayland-0'
2019-02-16 21:19:50 - [sway/input/keyboard.c:148] get_active_binding(modifiers=0)
2019-02-16 21:19:50 - [sway/input/keyboard.c:148] get_active_binding(modifiers=0)
2019-02-16 21:19:50 - [sway/input/keyboard.c:148] get_active_binding(modifiers=0)
2019-02-16 21:19:50 - [sway/input/keyboard.c:356] finding binding via state_keycodes
2019-02-16 21:19:50 - [sway/input/keyboard.c:148] get_active_binding(modifiers=0)
2019-02-16 21:19:50 - [sway/input/keyboard.c:360] finding binding via state_keysyms_translated
2019-02-16 21:19:50 - [sway/input/keyboard.c:148] get_active_binding(modifiers=0)
2019-02-16 21:19:50 - [sway/input/keyboard.c:365] finding binding via state_keysyms_raw
2019-02-16 21:19:50 - [sway/input/keyboard.c:148] get_active_binding(modifiers=0)
2019-02-16 21:19:50 - [sway/input/keyboard.c:148] get_active_binding(modifiers=1)
2019-02-16 21:19:50 - [sway/input/keyboard.c:148] get_active_binding(modifiers=0)
2019-02-16 21:19:50 - [sway/input/keyboard.c:148] get_active_binding(modifiers=1)
2019-02-16 21:19:50 - [sway/input/keyboard.c:356] finding binding via state_keycodes
2019-02-16 21:19:50 - [sway/input/keyboard.c:148] get_active_binding(modifiers=1)
2019-02-16 21:19:50 - [sway/input/keyboard.c:360] finding binding via state_keysyms_translated
2019-02-16 21:19:50 - [sway/input/keyboard.c:148] get_active_binding(modifiers=0)
2019-02-16 21:19:50 - [sway/input/keyboard.c:191] setting current_binding to nop 'BackSpace'
2019-02-16 21:19:50 - [sway/input/keyboard.c:365] finding binding via state_keysyms_raw
2019-02-16 21:19:50 - [sway/input/keyboard.c:148] get_active_binding(modifiers=1)
2019-02-16 21:19:50 - [sway/input/keyboard.c:187] encountered duplicate bindings nop 'BackSpace' and nop 'Shift+BackSpace'
2019-02-16 21:19:50 - [sway/commands/bind.c:331] running command for binding: nop 'BackSpace'
2019-02-16 21:19:50 - [sway/commands.c:253] Handling command 'nop 'BackSpace''
```

It seems like it erroneously finds the non-shifted binding via `state_keysyms_translated` (because for some reason the translation removes the shift), then when it later finds the correct binding in `state_keysyms_raw`, it ignores it as a duplicate.

### PR DESCRIPTION
**Pull request by bchallenor**
Allows both BackSpace and Shift+BackSpace to be bound under the US keyboard layout, per #3705, by making raw keysyms take precedence over translated keysyms.

Strictly speaking, only the call to `get_active_binding` needed to be reordered. I made the other changes for aesthetic consistency.

I haven't been running with this patch for long, but it does fix the issue for me.

@emersion 

Fixes #3705
Fixes #3079

### CODE REVIEW

**Comment by emersion** [comment]
Thanks!

**Comment by ddevault** [comment]
This should have been merged into master. We need to cherry pick that commit now.

**Comment by emersion** [comment]
Err, I haven't noticed the destination branch :\

**Comment by emersion** [comment]
Cherry-picked as https://github.com/swaywm/sway/commit/30931ad9e77b106956007530821d98bc20bca969

**Pull request merged**
