### PR TITLE
Translate readme to arabic

### PR DESCRIPTION
**Pull request by ashraf2033**
This pull request aims to resolve issue #7703

### CODE REVIEW

**Comment by kennylevinsen** [comment]
We will need a review from someone speaking Arabic. In the meantime, could you combine your commits into a single "Translate README to Arabic" commit?

**Review by 0xyosef — APPROVED** [review]
u can use "تثبيت" Instead of a word "تنصيب" 
and can write "الاسئله الشائعة"  Instead of ""

**Review by 0xyosef — CHANGES_REQUESTED** [review]
Nice 👌

**Comment by kennylevinsen** [comment]
LGTM if you could combine the commits again. :)

**Comment by 0xyosef** [comment]
> LGTM if you could combine the commits again. :)

What’s means LGTM ?

**Comment by kennylevinsen** [comment]
> What’s means LGTM ?

"Looks good to me", commonly used to indicate a passed review.

**Review by kennylevinsen — APPROVED** [review]

**Comment by kennylevinsen** [comment]
Thanks!

**Pull request merged**
