### PR TITLE
add links to i3 for first mention in README's

### PR DESCRIPTION
**Pull request by japhir**
Just occurred to me while reading through the readme, thought I could add it. May be a bit too much.

### CODE REVIEW

**Comment by ddevault** [comment]
Thanks! Can you squash this into a single commit?

**Comment by ddevault** [comment]
Thanks! And sorry - we just merged the German translation earlier today. Can you update it too and squash your work again?

**Comment by japhir** [comment]
> Thanks! Can you squash this into a single commit?

Yup, didn't do that initially because I did it all through the web interface :flushed:. 

I didn't change line indentation in the source, but some of the other lines are also longer than 80–100 columns, so I just left it as-is.

**Comment by ddevault** [comment]
Hmm, did you rebase or did you just copy the german readme in?

**Comment by japhir** [comment]
I failed, tried to update remote, merged the commit, then reset softly so I could squash the merge with the changes, but that of course created the new file again. Aaargh, sorry.

**Comment by ddevault** [comment]
Just do this:

```
git remote add upstream https://github.com/swaywm/sway
git fetch upstream
git rebase upstream/master
git push -f
```

**Comment by japhir** [comment]
Thanks! Gave me a merge conflict, but after resolving that I think this should work :)

**Comment by ddevault** [comment]
Thank you!

**Pull request merged**
