### PR TITLE
criteria: fullscreen mode criteria, fix #4222

### LINKED ISSUE #4222: Feature request: add fullscreen criteria
would be really nice to match against fullscreen (or fullscreen_mode?)
like:
`for_window [fullscreen] <command>`

### PR DESCRIPTION
**Pull request by versusvoid**

### CODE REVIEW

**Comment by emersion** [comment]
What is your use-case for this feature?

**Comment by versusvoid** [comment]
With status bar on top `move position 0 0` on fullscreen window will move it down a bar height, leaving black bar on top and cutting window's bottom.

**Comment by emersion** [comment]
Isn't this a bug? How does i3 behave?

**Comment by versusvoid** [comment]
I don't think it's a bug. User asks WM to move window, WM moves window.

Never used i3, so wouldn't know.

**Comment by emersion** [comment]
Please check how i3 behaves. We are an i3-compatible compositor, we should do what i3 does.

**Pull request closed without merging**
