### PR TITLE
[WIP] swaygrab: fix GCC warning

### PR DESCRIPTION
**Pull request by emersion**
GCC is so dumb

### CODE REVIEW

**Comment by emersion** [comment]
Build fails because of an outdated `pacman` flag.

**Comment by RedSoxFan** [comment]
> Build fails because of an outdated pacman flag.

Actually, it's a pacman bug: https://lists.archlinux.org/pipermail/pacman-dev/2018-June/022561.html

**Comment by emersion** [comment]
There are more of these: https://www.irccloud.com/pastebin/A4o46E0B/

We might just want to disable this stupid warning.

**Comment by martinetd** [comment]
yeah I really dislike the strncpy version of the warning. I've been changing a lot of strncpy to snprintf due to it recently, but it's a lot of effort of very little interest to me..

**Comment by ascent12** [comment]
>We might just want to disable this stupid warning.

Agreed. It's generally pretty annoying and useless.
Add -Wno-format-truncation while you're at it too (snprintf version of this warning).

>I've been changing a lot of strncpy to snprintf due to it recently

:+1: 
snprintf is by far a better function than str(n)cat/str(n)cpy, even when not talking about this warning.

**Comment by SirCmpwn** [comment]
We can just turn off -Werror for the 0.15 branch

**Comment by emersion** [comment]
Superseded by https://github.com/swaywm/sway/pull/2136

**Pull request closed without merging**
