### PR TITLE
Allow subsurfaces which overflow the container to be interacted with

### LINKED ISSUE #2492: Input is broken for popups in floating views
1. Open gnome-dictionary
2. Make it float, resize it to be small
3. Open the popover menu
4. Cannot click items outside the window geometry

### PR DESCRIPTION
**Pull request by RyanDwyer**
Fixes #2492.

### CODE REVIEW

**Comment by RyanDwyer** [comment]
Yeah, I think the rendering code needs to be changed in the same way, so it'll render in this order:

* Render unfocused views in the tiling layer
* Render focused view in the tiling layer if any (non-popups)
* Render unfocused views in the floating layer
* Render focused view in the floating layer if any (non-popups)
* Render popups

This means if the focused view's subsurfaces overflow the container, it'll be rendered on top of any siblings. And if there's an unfocused floating view on top of the subsurface, the subsurface will appear behind the floating view (I think this is desired, as subsurfaces could be non-popup-like things such as borders).

If this sounds good then I'll go ahead and implement it.

**Comment by emersion** [comment]
We could also just render everything in focus order.

**Comment by RyanDwyer** [comment]
> We could also just render everything in focus order.

No we can't, because an unfocused floating view must be rendered on top of a focused tiling view.

> Note: this isn't processing all popups before everything else (only the focused view's popups)

Only the focused view has popups. We close all popups when focus is changed.

**Comment by RyanDwyer** [comment]
How should we handle a case where two unfocused tiling siblings both have subsurfaces which overlap the other sibling? The only way to render that perfectly is to render the subsurfaces on a separate "layer" to the main surface. Meaning we'd iterate the tree and draw the main surfaces, then iterate it again and draw the subsurfaces. And if we did that, that would make this task easier as we wouldn't have to render the focused view separately.

This would change the rendering order to be:

* Render all main surfaces and decorations in the tiling layer
* Render all subsurfaces in the tiling layer
* Render all main surfaces, subsurfaces and decorations in the floating layer (ie. just render in the z-order)
* Render popups

The `container_at` code would have to be updated accordingly.

Can you think of any reason why this wouldn't work?

**Comment by emersion** [comment]
>No we can't, because an unfocused floating view must be rendered on top of a focused tiling view.

Of course, render each layer (tiling and floating) individually. The goal would just be to simplify a little all of this.

>Only the focused view has popups. We close all popups when focus is changed.

We can probably stop treating popups separately then.

>How should we handle a case where two unfocused tiling siblings both have subsurfaces which overlap the other sibling?

Subsurfaces are an integral part of the surface itself and can be placed under the main surface. You can't really order subsurfaces by layers across different surfaces.

IMHO we should just render everything in focus order (tiling then floating) and stop creating that many layers.

**Comment by RyanDwyer** [comment]
> IMHO we should just render everything in focus order (tiling then floating) and stop creating that many layers.

That would be pretty wasteful on CPU. If we iterate the focus stack then we need to do a `view_is_visible` check to skip rendering views which belong to different workspaces, and `view_is_visible` involves traversing up the ancestors. We also need to traverse the ancestors to see if any parent is focused so we can use the focused colours. And to render the children of a fullscreen container would involve a `container_has_ancestor` check.

Also, how would this work when it comes to multiseat and there are multiple focus stacks?

**Comment by emersion** [comment]
Adding more layers makes it even less maintainable.

**Comment by emersion** [comment]
Oh, and I might add: rendering in focus order is how all floating compositors work (and yes, GNOME uses focus order when it tiles views). So I wouldn't call it exactly a hack.

**Comment by SirCmpwn** [comment]
Is this ready to merge?

**Comment by RyanDwyer** [comment]
It's not perfect, but it solves more problems than it fixes so I'm happy for it to be merged.

Specifically, if you create `V[terminal gedit]`, resize gedit to be stupidly small, then open the `Open` menu in gedit, it appears over the terminal. If you then focus the terminal and move the cursor over the menu, the cursor events apply to the terminal instead of the menu.

**Comment by SirCmpwn** [comment]
Thanks! Make sure to file a follow-up ticket for that issue.

**Pull request merged**
