### PR TITLE
Fix output scale auto-detection

### PR DESCRIPTION
**Pull request by emersion**
Closes: https://github.com/swaywm/sway/issues/4960

### CODE REVIEW

**Comment by emersion** [comment]
Indeed! Fixed.

**Comment by RedSoxFan** [comment]
I think scale filter also needs to be moved back below scale and changed to use the pending scale.

**Comment by emersion** [comment]
Yeah, this seems broken as well. Pushed a bunch of other commits to simplify `apply_output_config`.

**Comment by RedSoxFan** [comment]
Thanks!

**Pull request merged**
