### PR TITLE
Re-add support for wlr_output's atomic API

### PR DESCRIPTION
**Pull request by emersion**
This reverts commit 724926ea6ae119956dc7b1e39c2e30c1e3657676 and
re-applies commit 6e0565e9de4247bbf0ca662565c58e0a54258d6e.

See also: https://github.com/swaywm/wlroots/pull/1797 (wlroots PR)
See also: https://github.com/swaywm/sway/pull/4355 (Original sway PR)
See also: https://github.com/swaywm/sway/pull/4434 (Revert sway PR)

### CODE REVIEW

**Comment by emersion** [comment]
This is now ready for review.

**Comment by escalade** [comment]
Fails to compile:

`/tmp/sway.eY5ULQ.ltrans5.ltrans.o:<artificial>:function load_main_config: error: undefined reference to 'set_color'
/tmp/sway.eY5ULQ.ltrans5.ltrans.o:<artificial>:function load_main_config: error: undefined reference to 'set_color'
/tmp/sway.eY5ULQ.ltrans5.ltrans.o:<artificial>:function load_main_config: error: undefined reference to 'set_color'
/tmp/sway.eY5ULQ.ltrans5.ltrans.o:<artificial>:function load_main_config: error: undefined reference to 'set_color'
`

**Comment by escalade** [comment]
Disregard last post, was not due to this PR.

**Comment by ddevault** [comment]
Thanks!

**Pull request merged**
