### PR TITLE
sway-output.5: improve display of parameter

### PR DESCRIPTION
**Pull request by tbm**
Since "width" and "height" are separate parameters, show them as such.

### CODE REVIEW

**Comment by tbm** [comment]
Someone mentioned this formatting issue on Reddit: https://www.reddit.com/r/swaywm/comments/wguayr/i_cant_seem_to_change_my_monitors_refreshrate_to/ij45lsz/

I'm also not sure why the parameters are uppercase but I left that.

**Comment by emersion** [comment]
Ah, I think they were upper-case to make them more readable with a lower-case "x" in the middle. I think I'd make sense to switch them to lower-case with this improved syntax.

**Comment by tbm** [comment]
> I think I'd make sense to switch them to lower-case with this improved syntax.

Updated the PR accordingly.

**Review by emersion — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
