### PR TITLE
Enclose macro replacement list in parentheses

### PR DESCRIPTION
**Pull request by t2b3**

### CODE REVIEW

**Comment by emersion** [comment]
Not a fan of these macro tricks. If the lack of parentheses is a bother, maybe we can switch these to proper `const` variables instead?

**Comment by t2b3** [comment]
I tried this but some switch statements require constant expressions (`#define`) 
`const` variables do not fulfill this requirement

**Comment by kennylevinsen** [comment]
I suppose C2X's `constexpr` would solve that.

**Comment by t2b3** [comment]
I think it is not so important, so just leave it for now.

**Pull request closed without merging**
