### PR TITLE
Optionally add focused window title to the bar

### PR DESCRIPTION
**Pull request by pedrocr**
When using sway without title bars it's useful to be able to display window titles in the bar.  Add a "window_title yes|no" bar command that displays the title of the focused window on the bar by reacting to window events.

### CODE REVIEW

**Comment by pedrocr** [comment]
Feature request submitted to i3 here:

https://github.com/i3/i3/issues/3774

**Comment by ddevault** [comment]
No thanks. I agree with @airblader's arguments against this for inclusion in i3.

**Comment by pedrocr** [comment]
This is disappointing. Note that the argument for i3 was that this could be done with the i3bar protocol and then it turned out it couldn't.

**Comment by emersion** [comment]
It's not possible because you want to align the title. This is a separate issue.

**Comment by pedrocr** [comment]
So a PR to extend the i3bar protocol with an alignment property would be acceptable?

**Comment by emersion** [comment]
Ref https://github.com/i3/i3/issues/1148

The question is whether or not the added complexity is acceptable, especially regarding clickable blocks.

**Comment by pedrocr** [comment]
That's why I'm asking before hacking on things. I'm leaning towards just keeping a local fork.

**Comment by pedrocr** [comment]
Note that clickable blocks are already part of the protocol:

https://i3wm.org/docs/i3bar-protocol.html

All that's really needed to replicate the current bar generically is a property that says if modules should be placed on the left or right of the bar. That doesn't seem too hard to do really.

**Pull request closed without merging**
