### PR TITLE
Restore previous tabbed layout behavior

### LINKED ISSUE #3002: Unable to make a tabbed layout
To reproduce:
Go to a new workspace
Create a new terminal
Set its layout to vertical
Try to set its layout to tabbed
Nothing will happen.

What this prevents:
Having 2 containers, side by side, with one being tabbed.

### PR DESCRIPTION
**Pull request by atomnuker**
As discussed in issue #3002 
Fixes #3002

### CODE REVIEW

**Comment by RyanDwyer** [comment]
I just want to make it clear that what we currently have implemented matches exactly what i3 does, and by merging this we are intentionally diverging from i3's behaviour.

That said, I'm fine with this.

**Comment by progandy** [comment]
It seems some people want this behaviour (#2912, #2987), maybe a configuration option is better like

    hide_lone_tabs

**Comment by SirCmpwn** [comment]
Follow-up ticket for the other behavior would be nice

**Comment by CodeJoule** [comment]
> I just want to make it clear that what we currently have implemented matches exactly what i3 does, and by merging this we are intentionally diverging from i3's behaviour.
> 
> That said, I'm fine with this.

Why is this? It confused me for about an hour, since my i3 config wasn't working as it should with Sway.

**Pull request merged**
