### PR TITLE
ci: add FreeBSD

### PR DESCRIPTION
**Pull request by emersion**
Obviously this currently fails because of `SOCK_CLOEXEC`.

### CODE REVIEW

**Comment by emersion** [comment]
Pushed a fix for ``SOCK_CLOEXEC``.

**Comment by emersion** [comment]
The builds haven't started (yet?), for some reason.

**Comment by ddevault** [comment]
Yeah, weird. Investigating.

**Comment by ddevault** [comment]
Github was dragging its feet delivering the webhook, it seems.

**Comment by emersion** [comment]
I think GitHub webhooks are behind, because the IRC push notifications are delayed too.

**Pull request merged**
