### PR TITLE
add persian README

### PR DESCRIPTION
**Pull request by AliChraghi**

### CODE REVIEW

**Comment by emersion** [comment]
Thanks. I'll wait for another native Persian speaker to approve this before merging.

**Review by siruidops — APPROVED** [review]
I'm native Persian speaker. I approve this text

**Comment by emersion** [comment]
Nice, thanks. @AliChraghi, can you add a link in the main README to the Persian translation?

**Review by mhdzli — CHANGES_REQUESTED** [review]
You should use `zws` anywhere you used a separated `ها` or `می` and add html tags to set `rtl` text direction

**Pull request closed without merging**
