### PR TITLE
Add Romanian translation to README

### PR DESCRIPTION
**Pull request by taminaru**
Hello, this is a Romanian translation of the README. If there are any errors or typos in it please notify me of them!

### CODE REVIEW

**Comment by taminaru** [comment]
Thank you for the improvements! This is so much better!

**Comment by TheEvilSkeleton** [comment]
> Thank you for the improvements! This is so much better!

don't forget to squash the commits :^)

**Comment by Xyene** [comment]
> Thank you for the improvements! This is so much better!

No problem!

Just in case you missed it, there's a "9 hidden conversations collapsed / Load more..." section containing a few more suggestions :slightly_smiling_face: 

In particular:
* in the English version, "Install dependencies" is using "Install" as a verb, but it was translated as an adjective -- it's not wrong per se, but changes the meaning (perhaps unintentionally, since the English version could be more clear there too)
* as far as I know, "valabil" has more of a connotation of "valid" than "available", which I think should be used when referring to a package
* typo'd lowercase î vs Î

The remainder are just small nits so take them with a grain of salt if they sound weird to you; I am in practice not a native speaker of the language.

**Comment by taminaru** [comment]
> > Thank you for the improvements! This is so much better!
> 
> No problem!
> 
> Just in case you missed it, there's a "9 hidden conversations collapsed / Load more..." section containing a few more suggestions 
> 
> In particular:
> 
> * in the English version, "Install dependencies" is using "Install" as a verb, but it was translated as an adjective -- it's not wrong per se, but changes the meaning (perhaps unintentionally, since the English version could be more clear there too)
> * as far as I know, "valabil" has more of a connotation of "valid" than "available", which I think should be used when referring to a package
> * typo'd lowercase î vs Î
> 
> The remainder are just small nits so take them with a grain of salt if they sound weird to you; I am in practice not a native speaker of the language.

Ah, sorry, I didn't actually notice them... I'll commit them now

**Comment by taminaru** [comment]
Thanks again for the improvements!

**Comment by Xyene** [comment]
> Ah, sorry, I didn't actually notice them... I'll commit them now

Hmm, I think you might've clicked the "Resolve conversation" buttons instead of "Commit suggestion" for these, since the diffs don't appear applied on https://github.com/swaywm/sway/pull/5452/files

Other than that -- looks good. If you could edit your commits to remove the spammy "Co-authored-by" flood that GitHub inserted every time a suggestion was applied and squash, we'll be good to go :slightly_smiling_face:

**Comment by emersion** [comment]
Gentle ping: do you have plans to rebase, squash the commits into a single one and edit the commit message?

**Comment by taminaru** [comment]
> Gentle ping: do you have plans to rebase, squash the commits into a single one and edit the commit message?

I have tried to rebase and squash even more but that is all it let me do. Some help would be appreciated ^^

**Comment by Xyene** [comment]
Sure;

```
 git rebase -i HEAD~2
```

image

exit editor, delete all of this:

image

exit editor again,

```
git push origin master --force
```

**Comment by taminaru** [comment]
Thanks! I will do it now.

**Comment by emersion** [comment]
See also https://git-rebase.io/ for more info

**Comment by taminaru** [comment]
I think I did it! Thank you guys again for the help :D

**Pull request merged**
