### PR TITLE
Enable borders on floating SSD xdg-shell views

### PR DESCRIPTION
**Pull request by emersion**
- [x] View is created after decoration mode is sent

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Bump

**Comment by emersion** [comment]
GTK doesn't send the decoration mode at all. I think the KDE folks fixed it, but it hasn't yet been released.

**Comment by emersion** [comment]
Works with `mpv`.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
