### PR TITLE
Add translation for chinese (zh-CN)

### PR DESCRIPTION
**Pull request by gaodacheng**

### CODE REVIEW

**Comment by ddevault** [comment]
Thanks! I'm looking for someone to review your work. In the meantime, can you update the top-level README with a link to yours?

**Comment by gaodacheng** [comment]
> In the meantime, can you update the top-level README with a link to yours?

Sure.

**Comment by doverride** [comment]
I ran this through Google Translate, Looks good.

**Comment by ddevault** [comment]
That's not how we do translations :smile:

**Comment by doverride** [comment]
Okay ,was just saying that this translation looks ok according to Google Translate (it translates back to english properly)

**Comment by ddevault** [comment]
Got some feedback from Chinese speakers off-Github. Thanks!

**Comment by 3TUSK** [comment]
> Looks like I am late on this one…

Two things that may be worth considering:

  - Typo: `如何这不可用, 请到` -> `如果这不可用, 请到`
  - Why this one uses half-width punctuations instead of full-with punctuations?

**Comment by gaodacheng** [comment]
> * Typo: `如何这不可用, 请到` -> `如果这不可用, 请到`

@3TUSK Thank you. The typo fixed in #4003.

**Pull request merged**
