### PR TITLE
Fix segfault in output_render

### LINKED ISSUE #2648: Segfault in output_render on hotplug
Steps to reproduce:

1. Configure swayidle:
```
exec swayidle \   
    before-sleep 'swaylock -i /home/somdoron/Pictures/lock2.jpg'
```
2. Run `systemctl suspend`
3. Sway crash

Backtrace:
```
#0  0x000000000041b56a in output_render (output=0x1b74450, when=0x7fffd4552a90, damage=0x7fffd4552a70)
    at ../sway/desktop/render.c:939
939		struct sway_container *fullscreen_con = NULL;
#1  0x0000000000417ef4 in damage_handle_frame (listener=0x1b745b0, data=0x1a64770) at ../sway/desktop/output.c:376
#2  0x00007fa10a6bd9f8 in wlr_signal_emit_safe (signal=0x1a647d0, data=0x1a64770) at ../util/signal.c:29
#3  0x00007fa10a6a9501 in output_handle_frame (listener=0x1a64868, data=0x138bfa0) at ../types/wlr_output_damage.c:50
#4  0x00007fa10a6bd9f8 in wlr_signal_emit_safe (signal=0x138c0b8, data=0x138bfa0) at ../util/signal.c:29
#5  0x00007fa10a6ac86f in wlr_output_send_frame (output=0x138bfa0) at ../types/wlr_output.c:534
#6  0x00007fa10a67c700 in page_flip_handler (fd=9, seq=777256, tv_sec=35854, tv_usec=712029, user=0x138bfa0)
    at ../backend/drm/drm.c:1095
#7  0x00007fa1062388ed in drmHandleEvent () at /lib64/libdrm.so.2
#8  0x00007fa10a67c762 in handle_drm_event (fd=9, mask=1, data=0x0) at ../backend/drm/drm.c:1105
#9  0x00007fa10a8f6f02 in wl_event_loop_dispatch (loop=0xd11f40, timeout=timeout@entry=-1) at src/event-loop.c:641
#10 0x00007fa10a8f5602 in wl_display_run (display=0xd14500) at src/wayland-server.c:1260
#11 0x00000000004155d0 in server_run (server=0x666a80 <server>) at ../sway/server.c:165
#12 0x0000000000414d9e in main (argc=1, argv=0x7fffd4553458) at ../sway/main.c:446
```

It seems `workspace` is null, I tried to check if `workspace` is null before assigning, that fixed the crash but then the machine didn't go into suspend at all, just stuck on the lock screen.

I'm building sway and wlroos from latest source.

### PR DESCRIPTION
**Pull request by emersion**
Fixes #2648

### CODE REVIEW

**Comment by RyanDwyer** [comment]
Any idea why the output has no workspace? Could it be that suspending causes wlroots to emit an output destroy event, so we move its workspaces, then the output is receiving a frame event? You could check `output->node.destroying` to see if that's the case.

**Comment by emersion** [comment]
(Checked the wlroots code, and we indeed check if the output is still connected before sending a frame event)

**Comment by RyanDwyer** [comment]
I'm going to try and reproduce this later so I can find the underlying issue. Is there anything special you need to do to reproduce it?

**Comment by RyanDwyer** [comment]
Thanks!

**Pull request merged**
