### PR TITLE
Auto-detect output scale

### PR DESCRIPTION
**Pull request by emersion**
If the screen DPI is high enough, auto-enable scale=2 (if the user
hasn't set the scale).

Uses heuristics based on [1].

[1]: https://gitlab.gnome.org/GNOME/mutter/blob/05217066171992b0bc50882869aad6385285c878/src/backends/meta-monitor.c#L1590

Closes: https://github.com/swaywm/sway/issues/1800

### CODE REVIEW

**Comment by tokyovigilante** [comment]
@emersion Looks great and very straightforward, however is there any consensus (from Gnome or elsewhere) about the HIDPI_LIMIT DPI of 192ppi? I have a Dell P2415Q which is a 24" 4K monitor at 183 DPI, and think 2x scaling is highly appropriate. Obviously I'm setting a scale factor anyway, but I'd argue 180 dpi at 40-50cm is reasonable to qualify for automatic scaling.

**Comment by emersion** [comment]
>however is there any consensus (from Gnome or elsewhere) about the HIDPI_LIMIT DPI of 192ppi?

192 = 96*2 (96 DPI is the standard LoDPI)

This PR's goal isn't to automatically scale *all* monitors, it's best-effort.

>The call to wlr_output_set_scale (currently L368 just inside the if (scale != wlr_output->scale)) needs to use scale not oc->scale

Oh, my bad. Fixed.

>oc->scale should now be set to 0 in default_output_config otherwise the outputs will still default to 1 after a reload

Hmm I'm not sure I follow. Wouldn't we have the same issue with `enabled` for instance?

**Comment by RedSoxFan** [comment]
> > oc->scale should now be set to 0 in default_output_config otherwise the outputs will still default to 1 after a reload
> 
> Hmm I'm not sure I follow. Wouldn't we have the same issue with `enabled` for instance?

`oc->scale` is set to `1` in `default_output_config`, which is only called when reloading. If the scale is not set in the config, then the scale will be `1` and avoid the detection until something causes the output config to be applied again. In `default_output_config`, it should either be `-1` or `0` not `1` so that the detection is used

**Comment by emersion** [comment]
Oh, silly mistake on my end again, I was reading `new_output_config` instead. Fixed.

**Comment by tokyovigilante** [comment]
> 192 = 96*2 (96 DPI is the standard LoDPI) 
> This PR's goal isn't to automatically scale _all_ monitors, it's best-effort.

No I understand that, just pointing out that's a relatively historical figure and seems to have been chosen for that reason alone (that it's double 96 DPI) by Gnome and whether this is a valid assumption in 2019. 

As noted elsewhere and in that Gnome bug/feature request, Windows and Apple (who arguably popularised the 2x/"Retina" standard for HIDPI scaling) both consider a lower DPI appropriate to scale to 2x, even as low as 150 DPI.  Obviously it also depends on your visual acuity and distance from screen too.

**Comment by emersion** [comment]
Yeah, that's fair. I personally ave a 161 DPI screen and 2x is too much.

**Comment by tokyovigilante** [comment]
Or would you consider making this configurable? I guess at that point you may as well just be setting it as an output option though,

**Comment by emersion** [comment]
The whole point is to not need to configure anything. It's an heuristic, if it doesn't work for some particular cases but still works for most others it's fine.

**Comment by tokyovigilante** [comment]
Yeah of course, I guess that's my point, that using 192 DPI as the cut-off for HIDPI is too high for my monitor, and using 160 DPI would be too low for yours, so I'm just asking if you'd agree that a 24" 4K screen should be scaled by default, and if so would you consider using 180 DPI as the cutoff.  If you want to stick with 192 DPI that's fine. 

The table "High Resolution/High Pixel Density Displays" [here (eizoglobal.com)](https://www.eizoglobal.com/library/basics/pixel_density_4k/) has a pretty big gap between desktop/external monitors at 100-150 dpi, other than 24" 4K (at ~185) and then HIDPI laptop monitors all over 200 dpi.

Unfortunately the Steam HW survey doesn't list DPI, only resolution, and only a handful of users have a screen > 1440p. Obviously gaming vs desktop use is different, but I haven't found any other useful resource for desktop DPI statistics.

**Comment by RedSoxFan** [comment]
Thanks!

**Pull request merged**
