### PR TITLE
Update wlroots xdg-shell-v6 API

### PR DESCRIPTION
**Pull request by emersion**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
This needs the corresponding xdg shell stable fixes too

**Comment by emersion** [comment]
Not implemented in sway yet (and let's not do it for now).

**Comment by SirCmpwn** [comment]
Build is failing here for wlr_renderer related reasons, are there other changes that need to be pulled forward?

**Comment by SirCmpwn** [comment]
Rebase this when you get the chance, I pushed a fix for the other issue to the wlroots branch

**Comment by emersion** [comment]
Rebased

**Comment by SirCmpwn** [comment]
I think I just committed the bulk of the work here myself, the diff is basically empty now

**Pull request closed without merging**
