### PR TITLE
Small fixes found by running scan-build and reading code

### PR DESCRIPTION
**Pull request by Emantor**
These are some smaller fixes for issues reported by running scan-build and reading the code.

### CODE REVIEW

**Comment by ianyfan** [comment]
I think only `sy` is being assigned to 0, should be `sx = 0, sy = 0`.

**Comment by Emantor** [comment]
Yes, will fix tomorrow.

**Comment by Emantor** [comment]
Should be fixed now.

**Comment by RedSoxFan** [comment]
Thanks!

**Pull request merged**
