### PR TITLE
Handle set_cursor requests from clients

### PR DESCRIPTION
**Pull request by emersion**
Allow clients to set a custom cursor if they have the seat's
pointer focus.

### CODE REVIEW

**Comment by emersion** [comment]
>This sets the cursor even if the view is on an invisible workspace

Not my bug™. The current code will give seat pointer focus to these (and send surface enter/motion events).

Will send another PR to fix it.

**Comment by acrisci** [comment]
:+1: good so far

**Comment by SirCmpwn** [comment]
Relevant

https://github.com/swaywm/sway/issues/1602

**Comment by emersion** [comment]
>This sets the cursor even if the view is on an invisible workspace

Fixed in #1669

**Comment by SirCmpwn** [comment]
tyvm

**Pull request merged**
