### PR TITLE
Spanish translation of the README

### PR DESCRIPTION
**Pull request by yabirgb**

### CODE REVIEW

**Comment by ddevault** [comment]
Can you update other READMEs with a link to the spanish TL?

**Comment by yabirgb** [comment]
@ddevault The others READMEs actually don't contain links to others READMEs. Aside the main one should I add anything to the others?

**Comment by ddevault** [comment]
Err, my bad. I wanted you to update the english readme with a link to yours.

**Comment by yabirgb** [comment]
Sorry. All fixed now.

**Comment by ddevault** [comment]
Thanks!

**Pull request merged**
