### PR TITLE
Backport for 1.8: fix build on Debian Stable

### PR DESCRIPTION
**Pull request by n3rdopolis**

### CODE REVIEW

**Comment by emersion** [comment]
Closing as a duplicate of #7287

**Comment by n3rdopolis** [comment]
OK, this one is for the 1.8 branch though. Will you backport 7287 instead?

**Comment by emersion** [comment]
Ah, didn't notice that.

Please wait for the original to be merged, then use `git cherry-pick -x` to pickup the commit, so that the original commit is linked from the backport.

**Comment by n3rdopolis** [comment]
OK, I have cherry-picked it

**Comment by emersion** [comment]
Thanks!

**Pull request merged**
