### PR TITLE
Fix presentation feedback when scanning out fullscreen view

### PR DESCRIPTION
**Pull request by emersion**
Closes: https://github.com/swaywm/sway/issues/4663

### CODE REVIEW

**Comment by tokyovigilante** [comment]
Between this commit and #1872 fullscreen mpv playback is working great now, however when verbose logging is enabled, I get 1000s of these messages in the log during playback 
```
[statusline] AV: 00:00:00 / 00:01:05 (0%) A-V: -0.041 DS: 2.000/0
[vo/gpu/vulkan/libplacebo] Allocating 12533760 of imported memory from fd: 36
[vo/gpu/vulkan/libplacebo] Allocating 12533760 of imported memory from fd: 36
[vo/gpu/vulkan/libplacebo] Freed slab of size 12533760 from imported fd: 44
[vo/gpu/vulkan/libplacebo] Freed slab of size 12533760 from imported fd: 44
[vo/gpu/vulkan/libplacebo] Freed slab of size 12533760 from imported fd: 36
[vo/gpu/vulkan/libplacebo] Freed slab of size 12533760 from imported fd: 36
[vo/gpu/vulkan/libplacebo] Allocating 12533760 of imported memory from fd: 36
[vo/gpu/vulkan/libplacebo] Allocating 12533760 of imported memory from fd: 36
[vo/gpu/vulkan/libplacebo] Allocating 12533760 of imported memory from fd: 36
[vo/gpu/vulkan/libplacebo] Allocating 12533760 of imported memory from fd: 36
[vo/gpu/vulkan/libplacebo] Allocating 536870912 memory of type 0xf (id 0) in heap 0
[statusline] AV: 00:00:00 / 00:01:05 (0%) A-V: -0.041 DS: 2.000/0
[cplayer] Change display sync audio drift: 1
[vo/gpu/vulkan/libplacebo] Freed slab of size 12533760 from imported fd: 36
[vo/gpu/vulkan/libplacebo] Freed slab of size 12533760 from imported fd: 36
[statusline] AV: 00:00:00 / 00:01:05 (0%) A-V:  0.066 DS: 3.500/0
[vo/gpu/vulkan/libplacebo] Allocating 12533760 of imported memory from fd: 36
[vo/gpu/vulkan/libplacebo] Allocating 12533760 of imported memory from fd: 36
[vo/gpu/vulkan/libplacebo] Freed slab of size 12533760 from imported fd: 36
[vo/gpu/vulkan/libplacebo] Freed slab of size 12533760 from imported fd: 36
[vo/gpu/vulkan/libplacebo] Freed slab of size 12533760 from imported fd: 36
[vo/gpu/vulkan/libplacebo] Freed slab of size 12533760 from imported fd: 36
[statusline] AV: 00:00:00 / 00:01:05 (0%) A-V:  0.066 DS: 3.500/0
[cplayer] Change display sync audio drift: -1
[statusline] AV: 00:00:00 / 00:01:05 (0%) A-V: -0.010 DS: 2.750/0 Dropped: 1
[vo/gpu/vulkan/libplacebo] Allocating 12533760 of imported memory from fd: 36
[vo/gpu/vulkan/libplacebo] Allocating 12533760 of imported memory from fd: 36
[vo/gpu/vulkan/libplacebo] Freed slab of size 12533760 from imported fd: 36
[vo/gpu/vulkan/libplacebo] Freed slab of size 12533760 from imported fd: 36
[vo/gpu/vulkan/libplacebo] Allocating 12533760 of imported memory from fd: 36
[vo/gpu/vulkan/libplacebo] Allocating 12533760 of imported memory from fd: 36
[vo/gpu/vulkan/libplacebo] Freed slab of size 12533760 from imported fd: 36
[vo/gpu/vulkan/libplacebo] Freed slab of size 12533760 from imported fd: 36
```
Implying that there is constant memory reallocation during playback. This is presumably why the memory leak was such an issue, but does this suggest mpv is not reusing buffers efficiently?

My current mpv.conf is
```
fs=yes
hwdec=auto
vo=gpu
gpu-api=vulkan
video-sync=display-resample
#profile=gpu-hq
#scale=ewa_lanczossharp
#cscale=ewa_lanczossharp
interpolation
tscale=oversample
```

**Comment by emersion** [comment]
cc @Dudemanguy

**Comment by Dudemanguy** [comment]
Yeah that definitely doesn't seem right. For vulkan, we let libplacebo handle the vast majority of it and its not clear to me why libplacebo would constantly reallocate slabs. I assume direct scanout is somehow related to this (since I don't get this behavior). It's a pity that apparently nothing I own has support for it.

**Comment by tokyovigilante** [comment]
I have seen this behaviour before direct scan-out, but didn't pay it too much attention. I'll rebuild a sway version before direct scan out and recheck. I'm using a X1 Yoga with UHD 620, and Mesa-git.

**Comment by Dudemanguy** [comment]
Hmm if direct scanout has nothing to do with this, I can try the latest mesa too and see what happens. It might be a driver issue.

**Comment by tokyovigilante** [comment]
Can confirm same behaviour with wlroots @ `b1b93c2c` and sway @ `8053aed9` which should predate direct scanout. I'm also using the new Iris driver and iHD/Intel Media Driver for VAAPI (both from mesa-git) if that would make a difference. Should I mention this over at the libplacebo repo?

**Comment by Dudemanguy** [comment]
Oh could you check if it happens with hardware decoding off real quick? If the same thing does happen, I guess it's worth a mention at libplacebo (although I think it's likely a driver bug). If not, it's definitely a driver bug. Regardless, it has nothing to do with direct scanout so we should probably not pollute this PR further.

**Comment by tokyovigilante** [comment]
No doesn't happen with SW decoding. I'll go and moan to #intel-3d I guess ;) You're right, this PR seems to work well regardless. Thanks!

**Comment by ddevault** [comment]
Thanks!

**Pull request merged**
