### PR TITLE
ext-session-lock: disable direct scan-out when locked

### PR DESCRIPTION
**Pull request by danieldg**
Fixes https://github.com/swaywm/swaylock/issues/236.

@alextsits - please confirm this fixes it for you.

### CODE REVIEW

**Review by Emantor — APPROVED** [review]
Makes sense to me.

**Comment by emersion** [comment]
I'd prefer to add the check in `scan_out_fullscreen_view`, which already contains similar checks for the overlay layer etc

**Comment by alextsits** [comment]
@danieldg thanks for this, I confirm it fixes https://github.com/swaywm/swaylock/issues/236 for me.

**Review by emersion — APPROVED** [review]
Thanks!

**Pull request merged**
