### PR TITLE
Fix window_type with disabled xwayland support

### PR DESCRIPTION
**Pull request by ppascher**
There were errors building with "enable-xwayland" set to "false" which were introduced by #2550.
This commit places those changes within "#ifdef HAVE_XWAYLAND" checks.

### CODE REVIEW

**Comment by emersion** [comment]
What about window role? Doesn't it need the same treatment?

**Comment by RyanDwyer** [comment]
Only `window_type` is needed because I had changed the data type to `enum atom_name`, and that datatype is defined in `xwayland.h`.

`window_role`, `class` and `instance` are all specific to xwayland but compile fine without xwayland support. Maybe they should all be inside the `HAVE_XWAYLAND` checks? We might also want to update the documentation to say which properties won't work without xwayland support.

**Comment by ppascher** [comment]
Thank you @emersion & @RyanDwyer . I placed those three criteria inside xwayland checks as you suggested.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
