### PR TITLE
Replace pcre with pcre2

### LINKED ISSUE #6838: Replace pcre with pcre2
Originally pcre was used to increase compatibility with i3 in #1151 however recently i3 was updated to use pcre2 instead: https://github.com/i3/i3/commit/6c7efc4de87efb1cbdfe2acbaa5def1d1d5fa8a5.

Because of this it would be quite good if sway did the same as pcre was deprecated a few years ago, incidentally improving compatibility with i3. (Although it might be useful to wait for the next i3 release, since the commit has not been tagged yet.)

### PR DESCRIPTION
**Pull request by ndren**
Thank you @psychon for fixing the patch I've sent over email. This should fix #6838.

### CODE REVIEW

**Comment by ndren** [comment]
I'm not too sure how to fix the build since pcre was not listed in any of the .yml build files. Any suggestions?

**Comment by emersion** [comment]
I guess the dependency wasn't explicit because base system packages depend on pcre v1, so we got it "by chance". We need to make the pcre v2 dep explicit in `.builds/*.yml`.

**Review by emersion — COMMENTED** [review]
Overall the code looks good to me!

**Comment by bl4ckb0ne** [comment]
The package seems to have a different name on alpine. Maybe drop the suffix after the 2?

```
$ apk search libpcre2
libpcre2-32-10.39-r0
libpcre2-16-10.39-r0
pcre2-dev-10.39-r0
pcre2-10.39-r0
```

**Comment by ndren** [comment]
Thank you, now it's building.

**Review by emersion — APPROVED** [review]
Thanks!

**Pull request merged**
