### PR TITLE
Add Turkish Translation for README.md

### PR DESCRIPTION
**Pull request by MuhammedTaha02**

### CODE REVIEW

**Comment by MuhammedTaha02** [comment]
@emersion

**Comment by emersion** [comment]
Needs another native speaker to review the translation.

**Comment by MuhammedTaha02** [comment]
I Understand

**Comment by fluix-dev** [comment]
emersion is referring to the fact that at least one other person who speaks the native language of the translation is required to leave a positive review.

However, it actually seems like this PR just adds a link to the Turkish README... but the link is a 404. Did you mean to also add the actual `README.tr.md` file but missed it when committing @MuhammedTaha02?

**Comment by fluix-dev** [comment]
Oh, I've since seen https://github.com/swaywm/sway/pull/6155. You should put this change as part of that one, not a separate PR just to add a link.

**Comment by MuhammedTaha02** [comment]
> Oh, I've since seen #6155. You should put this change as part of that one, not a separate PR just to add a link.

I made a mistake in the previous pr. And I couldn't delete it. Now I'm opening pr for translation again.

**Comment by emersion** [comment]
Please update your previous pull request by doing the change locally on your machine, without using GitHub's user interface.

**Pull request closed without merging**
