### PR TITLE
Support libappindicator

### PR DESCRIPTION
**Pull request by 4e554c4c**
See #1372

Menus for canonical (libappindicator) programs do not yet work, this will be added in a future PR as it is out of scope for #1431

### CODE REVIEW

**Comment by gnidorah** [comment]
@4e554c4c Wow, that some work, thank you much! With Steam I'm getting the following
```
10/24/17 21:42:17 - [sni_watcher.c:222] RegisterStatusNotifierItem called with "/org/ayatana/NotificationItem/steam"
10/24/17 21:42:17 - [dbus.c:17] Dispatching watch
10/24/17 21:42:17 - [dbus.c:113] Adding DBus timeout. Interval: 25s 0ms
10/24/17 21:42:17 - [dbus.c:17] Dispatching watch
10/24/17 21:42:17 - [dbus.c:120] Removing DBus timeout.
***10/24/17 21:42:17 - [icon.c:145] Could not find dir for theme: hicolor***
10/24/17 21:42:17 - [dbus.c:113] Adding DBus timeout. Interval: 25s 0ms
10/24/17 21:42:17 - [dbus.c:17] Dispatching watch
10/24/17 21:42:17 - [dbus.c:120] Removing DBus timeout.
***10/24/17 21:42:17 - [sni.c:60] Message is error: No such property `IconPixmap'***
***10/24/17 21:42:17 - [sni.c:175] Could not get icon from item***
```
Same with test app where icon is pointed by direct path.

**Comment by 4e554c4c** [comment]
Odd. Where is your theme directory? swaybar can't find it.

**Comment by SirCmpwn** [comment]
>I'd like some users to test this a bit before it gets merged because I don't have any libappindicator programs on my laptop that work correctly.

Wait, so did you write this without testing it at all yourself?

**Comment by gnidorah** [comment]
@4e554c4c I've put the theme at $HOME/.icons as per your code https://github.com/swaywm/sway/blob/master/swaybar/tray/icon.c#L100 and the first error gone, but two other remained and unfortunately no items were added to tray.

**Comment by gnidorah** [comment]
@4e554c4c I have a suspicion that libappindicator doesn't send IconPixmap, but either send icon name to look in theme or direct path to icon http://bazaar.launchpad.net/~indicator-applet-developers/libappindicator/trunk.16.10/view/head:/src/app-indicator.c#L1782
And probably you should look in $XDG_DATA_DIRS in addition to /usr/share when looking for themes? To support non-FHS distros like NixOS.

**Comment by gnidorah** [comment]
@4e554c4c Icons from theme work, yay! Thanks much for your work! :-) Icons by path will need another quirk.

**Comment by 4e554c4c** [comment]
It's supposed to check $XDG_DATA_DIRS, will check for bugs

**Comment by gnidorah** [comment]
@4e554c4c Sorry, I'm wrong then.

**Comment by gnidorah** [comment]
Current issues to resolve:
- [ ] For programs which create multiple icons, only one is created
- [ ] No menus created (mouse clicks do nothing)
- [ ] Programs report 'Unable to connect to the Notification Watcher: Timeout was reached'

**Comment by 4e554c4c** [comment]
I can fix the multiple icons. Canonical menus are tricky though because swaybar would have to draw them instead of the item.

**Comment by 4e554c4c** [comment]
@gnidorah See if 2f8cbbe fixes your issue with $XDG_DATA_DIRS

**Comment by gnidorah** [comment]
@4e554c4c Thank you much! Though I think it was my issue.

**Comment by gnidorah** [comment]
@4e554c4c 
> Allow correct item to get icon updates

Works great, thank you much!

**Comment by gnidorah** [comment]
@4e554c4c After this commit https://github.com/swaywm/sway/pull/1431/commits/92078345eab4ec5dfed567f951b4ed105f577b57 the tray script I use crashes the traybar with
```
process 16190: type struct 114 not a basic type
  D-Bus not built with -rdynamic so unable to print a backtrace
fish: 'swaybar -d --bar_id bar-0' terminated by signal SIGABRT (Abort)
```

**Comment by SirCmpwn** [comment]
>tray script I use

Well?

**Comment by SirCmpwn** [comment]
>D-Bus not built with -rdynamic so unable to print a backtrace

Well?

**Comment by 4e554c4c** [comment]
@gnidorah Sorry about that! See if 6ed5d6e fixes it.

**Comment by gnidorah** [comment]
@4e554c4c It is, thanks a lot!

**Comment by gnidorah** [comment]
@4e554c4c Thanks for the last commit! Works fine according to swaybar -d output.
BTW considering that there are many already useful tray fixes and improvements in this PR and considering that the sway-traymenu is some work and it will likely depend on wlroots, maybe it's better to split this PR into the two (ready and wip)?
1. 1888677f8810614776a92f19352e0b39b9cb4797..d5aa676bfbcdbbc7b9abbeb0a303b16b0ad69c24 for 0.15.2
2. WIP 2de973b99242f251f94d94a14799997ca978f0a7.. ...

**Comment by 4e554c4c** [comment]
@gnidorah sounds good to me!

**Comment by gnidorah** [comment]
@SirCmpwn @4e554c4c Thanks!

**Comment by 4e554c4c** [comment]
# Changes
+ SNI: Items can now be registered by DBus object path (@4e554c4c)
# New Features
+ SNI Icons: Icons can now be specified by absolute paths, rather than just icon names (@gnidorah)
+ SNI Icons: The tray will now look for icons in $XDG\_DATA\_DIRS and use the "default" theme (@4e554c4c)
# Bugs Fixed
+ SNI: Various segfaults and memory leaks fixed (@4e554c4c)
+ SNI Menus: Menus will be drawn on the bottom of the screen if the bar placement is bottom (@4e554c4c)
+ SNI Icons: Icons will now update on secondary outputs (@gnidorah)

**Pull request merged**
