### PR TITLE
swaybar: remove cursor code

### PR DESCRIPTION
**Pull request by ianyfan**
Fixes scaling issue in https://github.com/swaywm/sway/issues/1750

Someone tell me why this is a stupid thing to do :P

### CODE REVIEW

**Comment by emersion** [comment]
>Firstly, can sway distinguish between surfaces that don't use the pointer at all and ones that do, but don't set a cursor?

No

>Secondly, can there be valid cases where surfaces want to use the pointer but don't want/care to set the cursor?

Per the Wayland spec, no. If clients don't want a cursor, they can set it to NULL on enter.

**Comment by ianyfan** [comment]
> Per the Wayland spec, no. If clients don't want a cursor, they can set it to NULL on enter.

Doesn't that hide the cursor? What if it doesn't care to change it from what it already is?

**Comment by emersion** [comment]
"What it already is" is defined as "undefined" by the spec. It can be e.g. a resize cursor if it crossed a border before entering the surface.

**Comment by ianyfan** [comment]
Then you're suggesting that if a surface opens without setting a cursor because it just wants to display stuff, sway shouldn't change the cursor from what it was before?

**Comment by emersion** [comment]
Yes. Otherwise there's a race condition: sway will decide to change the cursor and maybe after the surface will set a different cursor. In the end the cursor will blink with sway's cursor before displaying the correct one.

This is sway's current behaviour. To test, open two terminals on two workspaces (caret cursor). When switching from one workspace to the other a normal cursor set by sway blinks.

**Comment by ianyfan** [comment]
But if instead sway doesn't change it, but the cursor moves into a window that doesn't set the cursor, and it's not a pointer, that feels wrong to me.

**Comment by emersion** [comment]
>a window that doesn't set the cursor

This is a client misbehaviour, per the spec.

**Comment by ianyfan** [comment]
Seems like a lot of boilerplate to me :(

**Pull request closed without merging**
